"""Phase 1 — deterministic, offline golden-SQL render harness (all 30 shapes).

Renders ``BoundQuery -> SQL`` for every shape in
``architecture_query-shape-catalog.md``, parametrized across the four target
dialects (postgres / bigquery / spark / tsql) where the producing path emits
dialect-translated SQL.  Two guarantees are enforced on every render:

1. **Self-parse invariant** — the rendered SQL is re-parsed in its own target
   dialect.  Any unparseable emission fails the test.  This structurally
   catches the Finding-1 class (literal ``(None)`` and similar malformed
   output) going forward, regardless of which code path produced it.
2. **Golden snapshot** — the rendered SQL is pinned to a file under
   ``tests/golden/render/``.  This is the refactor lock for Phase 3: any
   change in emitted SQL must be reviewed and re-pinned deliberately.

Goldens are regenerated by running with ``UPDATE_GOLDENS=1`` in the env.

Three offline-driveable producing paths are exercised:

* **source** — ``rewrite_for_source`` -> ``_build_source_sql``.  PostgreSQL is
  built logically then transpiled once at the boundary, so these render for
  ALL four dialects.
* **passthrough / SELECT *** — ``rewrite_for_source`` ->
  ``_substitute_table_names``.  This path does regex table substitution and
  preserves the input (PostgreSQL-canonical) SQL verbatim, then applies
  ``_requote_identifiers_for_dialect`` for all non-postgres targets.  Complex
  passthrough is pinned for ``postgres`` only (and SELECT * for ``postgres``
  + ``bigquery``); remaining cross-dialect passthrough expansions are tracked
  in the catalog G-series.
* **aggregate** — ``rewrite_for_aggregate`` against a pre-materialised
  aggregate definition.  Rendered for all four dialects.

Shapes that route through a *different* subsystem with its own dedicated test
suite (security wrap, pocket matcher, DAX translator, multi-source) are NOT
golden-rendered here; they are enumerated in :data:`SHAPE_COVERAGE` with their
owning suite, and :func:`test_all_30_shapes_accounted_for` asserts the full
1..30 set is covered so nothing is silently descoped.

The FakeDB scaffold mirrors the proven pattern in ``test_calculated_rewrite.py``
(dispatches ``select(Model)`` to pre-seeded row lists, supports ``db.get``).
"""
from __future__ import annotations

import os
import types
from pathlib import Path

import pytest
import sqlglot

from src.ir.logical_query import (
    BoundQuery,
    LogicalFilter,
    LogicalQuery,
    SelectExpression,
    SemanticBindingError,
)
from src.parsing.sql_parser import parse_sql_to_ir
from src.rewrite.query_rewriter import (
    _build_persona_star_sql,
    _build_source_sql,
    rewrite_for_aggregate,
    rewrite_for_source,
)

from shared.db.models import (
    DataSource,
    Dimension,
    Join,
    Measure,
    ModelColumn,
    ModelTable,
    UserDefinedAttribute,
)

MODEL_ID = "model-golden"
MODEL_SLUG = "golden"
ALL_DIALECTS = ["postgres", "bigquery", "spark", "tsql"]
PG_ONLY = ["postgres"]
PG_BQ = ["postgres", "bigquery"]
GOLDEN_DIR = Path(__file__).parent / "golden" / "render"


# ---------------------------------------------------------------------------
# Fake DB scaffold
# ---------------------------------------------------------------------------


class _Result:
    def __init__(self, rows):
        self._rows = list(rows)

    def scalars(self):
        return self

    def all(self):
        return list(self._rows)

    def scalar_one_or_none(self):
        return self._rows[0] if self._rows else None


class FakeDB:
    def __init__(self, *, tables=None, columns=None, joins=None, udas=None,
                 measures=None, dimensions=None, sources=None, connections=None):
        self.tables = list(tables or [])
        self.columns = list(columns or [])
        self.joins = list(joins or [])
        self.udas = list(udas or [])
        self.measures = list(measures or [])
        self.dimensions = list(dimensions or [])
        self.sources = list(sources or [])
        self.connections = list(connections or [])

    async def execute(self, stmt):
        entity = stmt.column_descriptions[0]["entity"]
        if entity is ModelTable:
            return _Result(self.tables)
        if entity is ModelColumn:
            return _Result(self.columns)
        if entity is Join:
            return _Result(self.joins)
        if entity is UserDefinedAttribute:
            return _Result(self.udas)
        if entity is Measure:
            return _Result(self.measures)
        if entity is Dimension:
            return _Result(self.dimensions)
        if entity is DataSource:
            return _Result(self.sources)
        raise AssertionError(f"Unexpected entity: {entity!r}")

    async def get(self, model_cls, pk):
        pool = {ModelTable: self.tables, ModelColumn: self.columns,
                DataSource: self.sources}.get(model_cls, [])
        for row in pool:
            if getattr(row, "id", None) == pk:
                return row
        return None


# ---------------------------------------------------------------------------
# Fixture builders
# ---------------------------------------------------------------------------


def _tbl(id_, physical_name, alias, table_type="fact"):
    return types.SimpleNamespace(
        id=id_, model_id=MODEL_ID, physical_name=physical_name,
        alias=alias, table_type=table_type, source_id="src-1",
    )


def _col(id_, table_id, column_name, data_type="text"):
    return types.SimpleNamespace(
        id=id_, model_table_id=table_id, column_name=column_name,
        data_type=data_type,
    )


def _dim(name, *, source_column_id=None, user_defined_attribute_id=None,
         is_time_dim=False):
    return types.SimpleNamespace(
        id=f"d-{name}", model_id=MODEL_ID, name=name,
        source_column_id=source_column_id,
        user_defined_attribute_id=user_defined_attribute_id,
        calc_expression=None, is_time_dim=is_time_dim, time_grain=None,
    )


def _meas(name, *, default_agg="sum", source_column_id=None,
          user_defined_attribute_id=None, measure_type="standard"):
    return types.SimpleNamespace(
        id=f"m-{name}", model_id=MODEL_ID, name=name,
        default_agg=default_agg, is_additive=True,
        measure_type=measure_type, source_column_id=source_column_id,
        user_defined_attribute_id=user_defined_attribute_id,
        expression=None, calc_agg_mode=None, variant_kind=None,
        variant_of_measure_id=None, variant_n=None,
        semi_additive_behavior=None,
    )


def _uda(id_, name, table_id, expression, *, output_data_type=None,
         validated=True, validation_error=None):
    return types.SimpleNamespace(
        id=id_, model_id=MODEL_ID, name=name, table_id=table_id,
        expression=expression, validated=validated,
        validation_error=validation_error, output_data_type=output_data_type,
    )


def _se(raw_text, *, classification, alias=None, agg_function=None,
        inner_column=None, inner_literal=None):
    return SelectExpression(
        raw_text=raw_text, alias=alias, classification=classification,
        agg_function=agg_function, inner_column=inner_column,
        inner_literal=inner_literal,
    )


def _bound(*, measures, dimensions=None, filters=None, grain=None,
           order_by=None, limit=None, offset=None, raw_query="SELECT 1",
           select_expressions=None, input_dialect="postgres",
           from_tables=None, has_passthrough_expressions=False,
           has_distinct=False, having_raw=None, select_star=False,
           has_unresolvable_order=False):
    dims = dimensions or []
    model = types.SimpleNamespace(
        id=MODEL_ID, slug=MODEL_SLUG, display_name="golden",
        deployed_version_id="v1",
    )
    lq = LogicalQuery(
        model_id=MODEL_ID, protocol="jdbc", raw_query=raw_query,
        requested_measures=[m.name for m in measures],
        requested_dimensions=[d.name for d in dims],
        filters=filters or [],
        grain=grain if grain is not None else [d.name for d in dims],
        order_by=order_by or [], limit=limit, offset=offset,
        query_fingerprint="fp-golden",
        select_expressions=select_expressions or [],
        from_tables=from_tables or [],
        input_dialect=input_dialect,
        has_distinct=has_distinct,
        having_raw=having_raw,
        select_star=select_star,
        has_unresolvable_order=has_unresolvable_order,
    )
    return BoundQuery(
        logical_query=lq, model=model, resolved_measures=measures,
        resolved_dimensions=dims, resolved_filters=filters or [],
        resolved_dimensions_by_name={d.name: d for d in dims},
        has_passthrough_expressions=has_passthrough_expressions,
    )


def _fact_db(*, dimensions=(), measures=(), udas=()):
    fact = _tbl("t-fact", "demo.sales", "f")
    cols = [
        _col("c-region", "t-fact", "region"),
        _col("c-amount", "t-fact", "amount", data_type="numeric"),
        _col("c-qty", "t-fact", "qty", data_type="integer"),
    ]
    return FakeDB(tables=[fact], columns=cols, measures=list(measures),
                  dimensions=list(dimensions), udas=list(udas))


def _join_db(*, dimensions=(), measures=(),
             fact_key="country_id", fact_key_type="integer",
             dim_key="id", dim_key_type="integer"):
    """Fact (demo.sales / alias 'f') joined to a dimension table
    (demo.country / alias 'd') on ``fact_key = dim_key``.  Varying the key
    data types drives the DATE/TIMESTAMP join-coercion path (#34)."""
    fact = _tbl("t-fact", "demo.sales", "f", table_type="fact")
    dimt = _tbl("t-dim", "demo.country", "d", table_type="dimension")
    cols = [
        _col("c-region", "t-fact", "region"),
        _col("c-amount", "t-fact", "amount", data_type="numeric"),
        _col("c-qty", "t-fact", "qty", data_type="integer"),
        _col("c-fkey", "t-fact", fact_key, data_type=fact_key_type),
        _col("c-dkey", "t-dim", dim_key, data_type=dim_key_type),
        _col("c-cname", "t-dim", "country_name"),
        _col("c-fperiod", "t-dim", "fiscal_period"),
    ]
    join = types.SimpleNamespace(
        id="j-1", model_id=MODEL_ID,
        left_table_id="t-fact", left_column_id="c-fkey",
        right_table_id="t-dim", right_column_id="c-dkey",
        join_type="inner",
    )
    return FakeDB(tables=[fact, dimt], columns=cols, joins=[join],
                  measures=list(measures), dimensions=list(dimensions))


# ---------------------------------------------------------------------------
# Aggregate-path scaffold (rewrite_for_aggregate is pure / offline).
# ---------------------------------------------------------------------------


def _agg_col(measure_name, stat_type):
    return types.SimpleNamespace(
        physical_col_name=f"{measure_name}__{stat_type}",
        stat_type=stat_type,
        measure=types.SimpleNamespace(name=measure_name) if measure_name else None,
    )


def _aggregate(grain, columns):
    return types.SimpleNamespace(
        id="agg-golden", grain=list(grain), columns=list(columns),
        status="active", physical_table_name="agg_golden",
        target_schema="aggregates", persona_id=None,
    )


def _agg_bind(sql, measures, dimensions, *, filters=None):
    lq = parse_sql_to_ir(sql, MODEL_ID)
    model = types.SimpleNamespace(
        id=MODEL_ID, slug=MODEL_SLUG, status="active",
        aggregations_enabled=True,
    )
    return BoundQuery(
        logical_query=lq, model=model, resolved_measures=measures,
        resolved_dimensions=dimensions, resolved_filters=filters or [],
        resolved_dimensions_by_name={d.name: d for d in dimensions},
    )


# ---------------------------------------------------------------------------
# Source-path scenarios  (rewrite_for_source -> _build_source_sql; all dialects)
# ---------------------------------------------------------------------------


def _s_group_by_sum():  # shape 1
    region = _dim("region", source_column_id="c-region")
    amount = _meas("amount", source_column_id="c-amount")
    bq = _bound(
        measures=[amount], dimensions=[region], grain=["region"],
        raw_query='SELECT region, SUM(amount) AS total FROM sales GROUP BY region',
        select_expressions=[
            _se('region', classification="passthrough", inner_column="region"),
            _se('SUM(amount)', classification="analytical", alias="total",
                agg_function="sum", inner_column="amount"),
        ],
    )
    return bq, _fact_db(dimensions=[region], measures=[amount])


def _s_multi_agg():  # shape 2
    amount = _meas("amount", source_column_id="c-amount")
    bq = _bound(
        measures=[amount], grain=[],
        raw_query="SELECT MIN(amount), MAX(amount) FROM sales",
        select_expressions=[
            _se('MIN(amount)', classification="analytical", agg_function="min",
                inner_column="amount"),
            _se('MAX(amount)', classification="analytical", agg_function="max",
                inner_column="amount"),
        ],
    )
    return bq, _fact_db(measures=[amount])


def _s_count_star():  # shape 4
    rc = _meas("__row_count", default_agg="count")
    bq = _bound(
        measures=[rc], from_tables=["sales"],
        raw_query="SELECT COUNT(*) FROM sales",
        select_expressions=[
            _se("COUNT(*)", classification="literal", agg_function="count",
                inner_literal="*"),
        ],
    )
    return bq, _fact_db(measures=[rc])


def _s_global_sum():  # shape 6
    amount = _meas("amount", source_column_id="c-amount")
    bq = _bound(
        measures=[amount], grain=[],
        raw_query="SELECT SUM(amount) AS total FROM sales",
        select_expressions=[
            _se("SUM(amount)", classification="analytical", alias="total",
                agg_function="sum", inner_column="amount"),
        ],
    )
    return bq, _fact_db(measures=[amount])


def _s_distinct():  # shape 16
    region = _dim("region", source_column_id="c-region")
    bq = _bound(
        measures=[], dimensions=[region], grain=["region"], has_distinct=True,
        raw_query="SELECT DISTINCT region FROM sales",
        select_expressions=[
            _se('region', classification="passthrough", inner_column="region"),
        ],
    )
    return bq, _fact_db(dimensions=[region])


def _s_having():  # shape 17
    region = _dim("region", source_column_id="c-region")
    amount = _meas("amount", source_column_id="c-amount")
    bq = _bound(
        measures=[amount], dimensions=[region], grain=["region"],
        having_raw="HAVING SUM(amount) > 100",
        raw_query="SELECT region, SUM(amount) FROM sales GROUP BY region "
                  "HAVING SUM(amount) > 100",
        select_expressions=[
            _se('region', classification="passthrough", inner_column="region"),
            _se('SUM(amount)', classification="analytical", agg_function="sum",
                inner_column="amount"),
        ],
    )
    return bq, _fact_db(dimensions=[region], measures=[amount])


def _s_order_limit():  # shapes 18 + 19
    region = _dim("region", source_column_id="c-region")
    amount = _meas("amount", source_column_id="c-amount")
    bq = _bound(
        measures=[amount], dimensions=[region], grain=["region"],
        order_by=[("region", "asc")], limit=10, offset=5,
        raw_query="SELECT region, SUM(amount) FROM sales GROUP BY region "
                  "ORDER BY region ASC LIMIT 10 OFFSET 5",
        select_expressions=[
            _se('region', classification="passthrough", inner_column="region"),
            _se('SUM(amount)', classification="analytical", agg_function="sum",
                inner_column="amount"),
        ],
    )
    return bq, _fact_db(dimensions=[region], measures=[amount])


def _s_filter_eq():  # filter predicate (eq) on source path
    region = _dim("region", source_column_id="c-region")
    amount = _meas("amount", source_column_id="c-amount")
    bq = _bound(
        measures=[amount], dimensions=[region], grain=["region"],
        filters=[LogicalFilter("region", "eq", "EMEA")],
        raw_query="SELECT region, SUM(amount) FROM sales "
                  "WHERE region = 'EMEA' GROUP BY region",
        select_expressions=[
            _se('region', classification="passthrough", inner_column="region"),
            _se('SUM(amount)', classification="analytical", agg_function="sum",
                inner_column="amount"),
        ],
    )
    return bq, _fact_db(dimensions=[region], measures=[amount])


def _s_filter_between():  # filter predicate (between) — Bug-918 path
    qty = _dim("qty", source_column_id="c-qty")
    amount = _meas("amount", source_column_id="c-amount")
    bq = _bound(
        measures=[amount], dimensions=[qty], grain=[],
        filters=[LogicalFilter("qty", "between", [1, 100])],
        raw_query="SELECT SUM(amount) FROM sales WHERE qty BETWEEN 1 AND 100",
        select_expressions=[
            _se('SUM(amount)', classification="analytical", agg_function="sum",
                inner_column="amount"),
        ],
    )
    return bq, _fact_db(dimensions=[qty], measures=[amount])


# --- Tier-1 expansion: semantic WHERE operators (catalog #31) --------------
# Existing filter_eq / filter_between already cover eq + between.  These two
# scenarios exercise the remaining LogicalFilter operators so each one's
# per-dialect predicate rendering is pinned.


def _s_filter_ops_a():  # shape 31 — gt / lte / neq / in / is_not_null
    region = _dim("region", source_column_id="c-region")
    qty = _dim("qty", source_column_id="c-qty")
    amount = _meas("amount", source_column_id="c-amount")
    bq = _bound(
        measures=[amount], dimensions=[region, qty], grain=["region"],
        filters=[
            LogicalFilter("qty", "gt", 5),
            LogicalFilter("qty", "lte", 100),
            LogicalFilter("region", "neq", "X"),
            LogicalFilter("region", "in", ["EMEA", "APAC"]),
            LogicalFilter("region", "is_not_null", None),
        ],
        raw_query="SELECT region, SUM(amount) FROM sales "
                  "WHERE qty > 5 AND qty <= 100 AND region <> 'X' "
                  "AND region IN ('EMEA','APAC') AND region IS NOT NULL "
                  "GROUP BY region",
        select_expressions=[
            _se('region', classification="passthrough", inner_column="region"),
            _se('SUM(amount)', classification="analytical", agg_function="sum",
                inner_column="amount"),
        ],
    )
    return bq, _fact_db(dimensions=[region, qty], measures=[amount])


def _s_filter_ops_b():  # shape 31 — gte / lt / not_in / like / is_null
    region = _dim("region", source_column_id="c-region")
    qty = _dim("qty", source_column_id="c-qty")
    amount = _meas("amount", source_column_id="c-amount")
    bq = _bound(
        measures=[amount], dimensions=[region, qty], grain=["region"],
        filters=[
            LogicalFilter("qty", "gte", 1),
            LogicalFilter("qty", "lt", 100),
            LogicalFilter("region", "not_in", ["ANTARCTICA"]),
            LogicalFilter("region", "like", "E%"),
            LogicalFilter("region", "is_null", None),
        ],
        raw_query="SELECT region, SUM(amount) FROM sales "
                  "WHERE qty >= 1 AND qty < 100 "
                  "AND region NOT IN ('ANTARCTICA') AND region LIKE 'E%' "
                  "AND region IS NULL GROUP BY region",
        select_expressions=[
            _se('region', classification="passthrough", inner_column="region"),
            _se('SUM(amount)', classification="analytical", agg_function="sum",
                inner_column="amount"),
        ],
    )
    return bq, _fact_db(dimensions=[region, qty], measures=[amount])


# --- Tier-1 expansion: single-source semantic join (catalog #33) -----------


def _s_join_basic():  # shape 33 — fact/dimension join, integer keys
    country = _dim("country_name", source_column_id="c-cname")
    amount = _meas("amount", source_column_id="c-amount")
    bq = _bound(
        measures=[amount], dimensions=[country], grain=["country_name"],
        raw_query="SELECT country_name, SUM(amount) FROM sales "
                  "JOIN country ON sales.country_id = country.id "
                  "GROUP BY country_name",
        select_expressions=[
            _se('country_name', classification="passthrough",
                inner_column="country_name"),
            _se('SUM(amount)', classification="analytical", agg_function="sum",
                inner_column="amount"),
        ],
    )
    return bq, _join_db(dimensions=[country], measures=[amount])


# --- Tier-1 expansion: DATE/TIMESTAMP join coercion (catalog #34) ----------


def _s_join_date_coercion():  # shape 34 — TIMESTAMP fact key / DATE dim key
    period = _dim("fiscal_period", source_column_id="c-fperiod")
    amount = _meas("amount", source_column_id="c-amount")
    bq = _bound(
        measures=[amount], dimensions=[period], grain=["fiscal_period"],
        raw_query="SELECT fiscal_period, SUM(amount) FROM sales "
                  "JOIN country ON sales.event_ts = country.cal_date "
                  "GROUP BY fiscal_period",
        select_expressions=[
            _se('fiscal_period', classification="passthrough",
                inner_column="fiscal_period"),
            _se('SUM(amount)', classification="analytical", agg_function="sum",
                inner_column="amount"),
        ],
    )
    db = _join_db(
        dimensions=[period], measures=[amount],
        fact_key="event_ts", fact_key_type="timestamp",
        dim_key="cal_date", dim_key_type="date",
    )
    return bq, db


# --- Tier-1 expansion: UDA-backed dimension / measure (catalog #35 / #36) ---


def _s_uda_dimension():  # shape 35 — UDA expression as a dimension
    cohort = _dim("cohort", user_defined_attribute_id="u-cohort")
    amount = _meas("amount", source_column_id="c-amount")
    uda = _uda("u-cohort", "cohort_bucket", "t-fact",
               "CASE WHEN amount > 100 THEN 'high' ELSE 'low' END")
    bq = _bound(
        measures=[amount], dimensions=[cohort], grain=["cohort"],
        raw_query="SELECT cohort, SUM(amount) FROM sales GROUP BY cohort",
        select_expressions=[
            _se('cohort', classification="passthrough", inner_column="cohort"),
            _se('SUM(amount)', classification="analytical", agg_function="sum",
                inner_column="amount"),
        ],
    )
    return bq, _fact_db(dimensions=[cohort], measures=[amount], udas=[uda])


def _s_uda_measure():  # shape 36 — UDA expression aggregated as a measure
    region = _dim("region", source_column_id="c-region")
    profit = _meas("profit", default_agg="sum",
                   user_defined_attribute_id="u-profit")
    uda = _uda("u-profit", "profit_expr", "t-fact", "amount - qty")
    bq = _bound(
        measures=[profit], dimensions=[region], grain=["region"],
        raw_query="SELECT region, SUM(amount - qty) AS profit FROM sales "
                  "GROUP BY region",
        select_expressions=[
            _se('region', classification="passthrough", inner_column="region"),
            _se('SUM(amount - qty)', classification="analytical", alias="profit",
                agg_function="sum", inner_column="profit"),
        ],
    )
    return bq, _fact_db(dimensions=[region], measures=[profit], udas=[uda])


# --- Tier-1 expansion: date/time CAST filter coercion (catalog #108) -------


def _s_filter_cast_coercion():  # shape 108 — CAST(...AS DATE) col coerces value
    # A UDA dimension whose expression casts a TIMESTAMP column to DATE.  A
    # filter literal against it must be wrapped CAST(<lit> AS DATE) so a
    # DATE expression is not compared to a bare string/timestamp literal.
    event_day = _dim("event_day", user_defined_attribute_id="u-eventday")
    amount = _meas("amount", source_column_id="c-amount")
    uda = _uda("u-eventday", "event_day", "t-fact",
               "CAST(event_ts AS DATE)", output_data_type="date")
    bq = _bound(
        measures=[amount], dimensions=[event_day], grain=["event_day"],
        filters=[LogicalFilter("event_day", "eq", "2024-01-15")],
        raw_query="SELECT CAST(event_ts AS DATE) AS event_day, SUM(amount) "
                  "FROM sales WHERE CAST(event_ts AS DATE) = '2024-01-15' "
                  "GROUP BY event_day",
        select_expressions=[
            _se('event_day', classification="passthrough",
                inner_column="event_day"),
            _se('SUM(amount)', classification="analytical", agg_function="sum",
                inner_column="amount"),
        ],
    )
    return bq, _fact_db(dimensions=[event_day], measures=[amount], udas=[uda])


# ---------------------------------------------------------------------------
# Passthrough scenarios  (rewrite_for_source -> _substitute_table_names).
# Raw SQL references the model slug "golden"; the table is substituted with the
# physical reference and the rest is preserved verbatim (postgres-canonical).
# ---------------------------------------------------------------------------


def _pass(raw_query, *, select_star=False):
    bq = _bound(
        measures=[], dimensions=[], grain=[],
        from_tables=[MODEL_SLUG], raw_query=raw_query,
        has_passthrough_expressions=not select_star, select_star=select_star,
    )
    return bq, _fact_db()


def _s_detail():  # shape 7 — detail query, no aggregation
    return _pass("SELECT region, amount, qty FROM golden")


def _s_compound_ratio():  # shape 8 — SUM/SUM
    return _pass("SELECT SUM(amount) / SUM(qty) AS ratio FROM golden")


def _s_case_expr():  # shape 9 — CASE/COALESCE/UPPER
    return _pass(
        "SELECT CASE WHEN amount > 0 THEN 'pos' ELSE 'neg' END AS sign, "
        "COUNT(*) AS n FROM golden "
        "GROUP BY CASE WHEN amount > 0 THEN 'pos' ELSE 'neg' END"
    )


def _s_func_grain():  # shape 10 — function-grain GROUP BY
    return _pass(
        "SELECT EXTRACT(YEAR FROM ts) AS yr, COUNT(*) AS n FROM golden "
        "GROUP BY EXTRACT(YEAR FROM ts)"
    )


def _s_string_concat():  # shape 11 — string concatenation
    return _pass("SELECT region || '-' || region AS label FROM golden")


def _s_subquery():  # shape 12 — subquery wrapper
    return _pass(
        "SELECT sub.region FROM (SELECT region FROM golden) AS sub"
    )


def _s_cte():  # shape 13 — CTE
    return _pass(
        "WITH t AS (SELECT region, amount FROM golden) SELECT region FROM t"
    )


def _s_window():  # shape 14 — window function
    return _pass(
        "SELECT region, SUM(amount) OVER (PARTITION BY region) AS running "
        "FROM golden"
    )


def _s_select_star():  # shape 15 — SELECT *
    return _pass("SELECT * FROM golden", select_star=True)


def _s_scalar_round():  # shape 20 — scalar wrapping aggregate
    return _pass("SELECT ROUND(SUM(amount), 2) AS r FROM golden")


def _s_distinct_on():  # shape 30 — DISTINCT ON
    return _pass(
        "SELECT DISTINCT ON (region) region, amount FROM golden ORDER BY region"
    )


# ---------------------------------------------------------------------------
# Aggregate-path scenarios  (rewrite_for_aggregate; all dialects).
# ---------------------------------------------------------------------------


def _a_avg_decomp():  # shape 3 — AVG = SUM/COUNT decomposition
    m = _meas("risk_score", default_agg="avg")
    d = _dim("country_code")
    agg = _aggregate(
        ["country_code"],
        [_agg_col("risk_score", "sum"), _agg_col("risk_score", "count")],
    )
    bq = _agg_bind(
        "SELECT country_code, AVG(risk_score) FROM golden GROUP BY country_code",
        [m], [d],
    )
    return bq, agg


def _a_avg_stored_coarser():  # shape 3b — stored avg col present, coarser grain (F-004-01)
    m = _meas("risk_score", default_agg="avg")
    d = _dim("country_code")
    agg = _aggregate(
        ["country_code", "event_type"],
        [
            _agg_col("risk_score", "avg"),
            _agg_col("risk_score", "sum"),
            _agg_col("risk_score", "count"),
        ],
    )
    bq = _agg_bind(
        "SELECT country_code, AVG(risk_score) FROM golden GROUP BY country_code",
        [m], [d],
    )
    return bq, agg


def _a_avg_stored_exact():  # shape 3c — stored avg col present, exact grain
    m = _meas("risk_score", default_agg="avg")
    d = _dim("country_code")
    agg = _aggregate(
        ["country_code"],
        [
            _agg_col("risk_score", "avg"),
            _agg_col("risk_score", "sum"),
            _agg_col("risk_score", "count"),
        ],
    )
    bq = _agg_bind(
        "SELECT country_code, AVG(risk_score) FROM golden GROUP BY country_code",
        [m], [d],
    )
    return bq, agg


def _a_reagg_coarser():  # shape 5 — re-aggregation at coarser grain
    m = _meas("amount", default_agg="sum")
    d = _dim("country_code")
    agg = _aggregate(
        ["country_code", "event_type"], [_agg_col("amount", "sum")],
    )
    bq = _agg_bind(
        "SELECT country_code, SUM(amount) FROM golden GROUP BY country_code",
        [m], [d],
    )
    return bq, agg


def _a_nonadditive_minmax():  # shape 21 — non-additive MIN at exact grain
    m = _meas("amount", default_agg="min")
    d = _dim("country_code")
    agg = _aggregate(["country_code"], [_agg_col("amount", "min")])
    bq = _agg_bind(
        "SELECT country_code, MIN(amount) FROM golden GROUP BY country_code",
        [m], [d],
    )
    return bq, agg


# ---------------------------------------------------------------------------
# Scenario registries.  Each value: (builder, dialects, shape_no).
# ---------------------------------------------------------------------------


SOURCE_SCENARIOS = {
    "group_by_sum": (_s_group_by_sum, ALL_DIALECTS, 1),
    "multi_agg": (_s_multi_agg, ALL_DIALECTS, 2),
    "count_star": (_s_count_star, ALL_DIALECTS, 4),
    "global_sum": (_s_global_sum, ALL_DIALECTS, 6),
    "distinct": (_s_distinct, ALL_DIALECTS, 16),
    "having": (_s_having, ALL_DIALECTS, 17),
    "order_limit": (_s_order_limit, ALL_DIALECTS, 19),
    "filter_eq": (_s_filter_eq, ALL_DIALECTS, None),
    "filter_between": (_s_filter_between, ALL_DIALECTS, None),
    # Tier-1 expansion (catalog #31-#36, #108).
    "filter_ops_a": (_s_filter_ops_a, ALL_DIALECTS, 31),
    "filter_ops_b": (_s_filter_ops_b, ALL_DIALECTS, 31),
    "join_basic": (_s_join_basic, ALL_DIALECTS, 33),
    "join_date_coercion": (_s_join_date_coercion, ALL_DIALECTS, 34),
    "uda_dimension": (_s_uda_dimension, ALL_DIALECTS, 35),
    "uda_measure": (_s_uda_measure, ALL_DIALECTS, 36),
    "filter_cast_coercion": (_s_filter_cast_coercion, ALL_DIALECTS, 108),
}

PASSTHROUGH_SCENARIOS = {
    "detail": (_s_detail, PG_ONLY, 7),
    "compound_ratio": (_s_compound_ratio, PG_ONLY, 8),
    "case_expr": (_s_case_expr, PG_ONLY, 9),
    "func_grain": (_s_func_grain, PG_ONLY, 10),
    "string_concat": (_s_string_concat, PG_ONLY, 11),
    "subquery": (_s_subquery, PG_ONLY, 12),
    "cte": (_s_cte, PG_ONLY, 13),
    "window": (_s_window, PG_ONLY, 14),
    "select_star": (_s_select_star, PG_BQ, 15),
    "scalar_round": (_s_scalar_round, PG_ONLY, 20),
    "distinct_on": (_s_distinct_on, PG_ONLY, 30),
}

# Source and passthrough share the same async driver (rewrite_for_source).
RENDER_SCENARIOS = {**SOURCE_SCENARIOS, **PASSTHROUGH_SCENARIOS}

AGGREGATE_SCENARIOS = {
    "avg_decomp": (_a_avg_decomp, ALL_DIALECTS, 3),
    "avg_stored_coarser": (_a_avg_stored_coarser, ALL_DIALECTS, 3),
    "avg_stored_exact": (_a_avg_stored_exact, ALL_DIALECTS, 3),
    "reagg_coarser": (_a_reagg_coarser, ALL_DIALECTS, 5),
    "nonadditive_minmax": (_a_nonadditive_minmax, ALL_DIALECTS, 21),
}


def _flatten(scenarios):
    return [(name, d) for name, (_, dialects, _no) in scenarios.items()
            for d in dialects]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _assert_self_parses(sql: str, dialect: str) -> None:
    """Self-parse invariant: rendered SQL must re-parse in its own dialect."""
    parsed = sqlglot.parse_one(sql, read=dialect)
    assert parsed is not None, f"Rendered SQL parsed to None ({dialect}): {sql}"


def _check_golden(name: str, actual: str) -> None:
    GOLDEN_DIR.mkdir(parents=True, exist_ok=True)
    path = GOLDEN_DIR / f"{name}.sql"
    if os.environ.get("UPDATE_GOLDENS"):
        path.write_text(actual + "\n", encoding="utf-8")
        return
    assert path.exists(), (
        f"Missing golden {path.name}. Re-run with UPDATE_GOLDENS=1 to create it."
    )
    expected = path.read_text(encoding="utf-8").rstrip("\n")
    assert actual == expected, (
        f"Golden mismatch for {name}.\n"
        f"  expected: {expected}\n"
        f"  actual:   {actual}\n"
        f"If this change is intentional, re-run with UPDATE_GOLDENS=1."
    )


def _common_assertions(sql: str, shape: str, dialect: str) -> None:
    assert isinstance(sql, str) and sql.strip()
    # Finding-1 negative invariant: the literal "(None)" must never leak.
    assert "(None)" not in sql, f"Literal (None) leaked into {shape}/{dialect}: {sql}"
    _assert_self_parses(sql, dialect)
    _check_golden(f"{shape}__{dialect}", sql)


# ---------------------------------------------------------------------------
# Parametrized golden + self-parse tests
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
@pytest.mark.parametrize("shape,dialect", _flatten(RENDER_SCENARIOS))
async def test_render_golden_source(shape, dialect):
    """Source + passthrough + SELECT * shapes via ``rewrite_for_source``."""
    bq, db = RENDER_SCENARIOS[shape][0]()
    sql = await rewrite_for_source(bq, db, target_dialect=dialect)
    _common_assertions(sql, shape, dialect)


@pytest.mark.parametrize("shape,dialect", _flatten(AGGREGATE_SCENARIOS))
def test_render_golden_aggregate(shape, dialect):
    """Aggregate-routed shapes via ``rewrite_for_aggregate``."""
    bq, agg = AGGREGATE_SCENARIOS[shape][0]()
    sql = rewrite_for_aggregate(bq, agg, target_dialect=dialect)
    _common_assertions(sql, shape, dialect)


# ---------------------------------------------------------------------------
# 30-shape coverage registry + completeness guard (anti-descoping).
# ---------------------------------------------------------------------------


# The order_limit scenario renders LIMIT, OFFSET *and* ORDER BY in one query,
# so it covers both catalog shapes 18 and 19.
COMBINED_RENDERED = {18: "order_limit (combined with shape 19)"}


def _rendered_shape_map() -> dict[int, str]:
    out: dict[int, str] = dict(COMBINED_RENDERED)
    for name, (_b, _d, no) in {**RENDER_SCENARIOS, **AGGREGATE_SCENARIOS}.items():
        if no is not None:
            out[no] = name
    return out


# Shapes covered by a dedicated subsystem suite (out of this harness's render
# scope by design) or a documented coverage gap.  Mapped here so the 1..30 set
# is provably complete and nothing is silently descoped.
SHAPE_COVERAGE_OWNED = {
    22: "pocket matcher — tests/test_pocket_matcher.py (feature-gated; catalog G-1)",
    23: "row security — tests/test_row_security_compiler.py + validate_security.py SR01-SR06",
    24: "persona gate — validate_security.py SP01-SP06 / SB01-SB04",
    25: "multi-source model — coverage gap G-2 (requires two source DBs)",
    26: "DAX-translated SQL — XMLA DAX translator (UAT batches; catalog G-3)",
    27: "calculated measure — tests/test_calculated_rewrite.py",
    28: "time-variant measure — tests/test_dax_time_variants.py",
    29: "semi-additive measure — tests/test_semi_additive.py",
}


CORE_CATALOG = set(range(1, 31))

# Tier-1 expansion shapes (catalog #31-#98) that this harness now renders as
# golden cases.  #37 (invalid UDA) is a regression assertion, not a golden, and
# is verified by ``test_f37_invalid_uda_raises`` below.
EXPANSION_RENDERED = {31, 33, 34, 35, 36, 108}


def test_all_30_shapes_accounted_for():
    """Every core shape 1..30 in the catalog is either golden-rendered here or
    explicitly owned by a named suite.  Fails loudly if a shape is dropped."""
    rendered = set(_rendered_shape_map())
    owned = set(SHAPE_COVERAGE_OWNED)
    core_rendered = {n for n in rendered if n in CORE_CATALOG}
    covered = core_rendered | owned
    missing = CORE_CATALOG - covered
    assert not missing, f"Shapes not accounted for: {sorted(missing)}"
    overlap = core_rendered & owned
    assert not overlap, f"Shapes double-classified (rendered + owned): {sorted(overlap)}"
    assert covered == CORE_CATALOG, f"Unexpected core shape ids: {sorted(covered)}"


def test_tier1_expansion_shapes_rendered():
    """The Tier-1 catalog-expansion shapes (#31, #33-#36, #108) are each
    golden-rendered here, so the expansion is not silently descoped."""
    rendered = set(_rendered_shape_map())
    missing = EXPANSION_RENDERED - rendered
    assert not missing, f"Tier-1 expansion shapes not rendered: {sorted(missing)}"


# ---------------------------------------------------------------------------
# Finding-1 / Bug-917 regression — unresolved UDA must not emit "(None)".
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_f1_unresolved_uda_no_none_literal():
    """A dimension whose UDA table is absent from the FROM clause has no
    resolvable physical mapping.  Before Bug-917 the ``_get_phys_expr`` path
    emitted the literal string ``(None)``; the Bug-917 fix removed that.

    Phase 2 (fail-loud, Findings 2 & 3) goes further: such an unresolved
    dimension must raise a clear ``SemanticBindingError`` naming the object
    rather than fall through to a bare-identifier fallback.  The diagnostic
    must never contain a ``None`` literal (Bug-917 spirit)."""
    # cohort's UDA points at a table id that does not exist -> the UDA
    # expression is never built -> the dimension has no physical mapping.
    cohort = _dim("cohort", user_defined_attribute_id="u-missing")
    amount = _meas("amount", source_column_id="c-amount")
    orphan_uda = _uda("u-missing", "cohort_bucket", "t-absent",
                      "CASE WHEN x THEN 'a' ELSE 'b' END")

    bq = _bound(
        measures=[amount], dimensions=[cohort], grain=[],
        raw_query="SELECT UPPER(cohort), SUM(amount) FROM sales",
        select_expressions=[
            _se("UPPER(cohort)", classification="passthrough"),
            _se('SUM(amount)', classification="analytical", agg_function="sum",
                inner_column="amount"),
        ],
    )
    db = _fact_db(dimensions=[cohort], measures=[amount], udas=[orphan_uda])

    with pytest.raises(SemanticBindingError, match="cohort") as excinfo:
        await _build_source_sql(bq, db, target_dialect="postgres")

    # Bug-917 spirit: the diagnostic must never leak a None literal.
    assert "(None)" not in str(excinfo.value)
    assert "None" not in str(excinfo.value)


# ---------------------------------------------------------------------------
# Finding-6 / Bug-919 regression — passthrough parsed in the input dialect.
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_f6_passthrough_uses_input_dialect():
    """A passthrough expression written with BigQuery backtick identifiers
    must be parsed with ``read=input_dialect`` so its column gets qualified to
    the physical column.  A hardcoded ``read='postgres'`` (the pre-fix bug)
    cannot tokenize backticks and falls through to verbatim, leaving the
    column unqualified."""
    region = _dim("region", source_column_id="c-region")
    bq = _bound(
        measures=[], dimensions=[region], grain=[],
        input_dialect="bigquery",
        raw_query="SELECT `region` FROM sales",
        select_expressions=[
            _se("`region`", classification="passthrough"),
        ],
    )
    db = _fact_db(dimensions=[region])

    sql = await _build_source_sql(bq, db, target_dialect="postgres")

    # Parsed via bigquery -> column resolved -> qualified physical reference.
    assert '"f"."region"' in sql, f"input_dialect not honored: {sql}"
    _assert_self_parses(sql, "postgres")


# ---------------------------------------------------------------------------
# Catalog #37 regression — an invalid UDA must fail loud (named diagnostic),
# never emit raw None / a semantic-name fallback / silently wrong SQL.
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_f37_invalid_uda_raises():
    """A UDA whose ``validated`` flag is False must raise a clear ValueError
    naming the attribute, rather than rendering a fallback expression."""
    cohort = _dim("cohort", user_defined_attribute_id="u-bad")
    amount = _meas("amount", source_column_id="c-amount")
    bad_uda = _uda("u-bad", "cohort_bucket", "t-fact",
                   "CASE WHEN amount > THEN 'a' END",
                   validated=False, validation_error="syntax error near THEN")
    bq = _bound(
        measures=[amount], dimensions=[cohort], grain=["cohort"],
        raw_query="SELECT cohort, SUM(amount) FROM sales GROUP BY cohort",
        select_expressions=[
            _se('cohort', classification="passthrough", inner_column="cohort"),
            _se('SUM(amount)', classification="analytical", agg_function="sum",
                inner_column="amount"),
        ],
    )
    db = _fact_db(dimensions=[cohort], measures=[amount], udas=[bad_uda])

    with pytest.raises(ValueError, match="cohort_bucket"):
        await _build_source_sql(bq, db, target_dialect="postgres")


# ---------------------------------------------------------------------------
# Phase 2 fail-loud (Findings 2 & 3) — unresolved logical->physical mappings
# must raise a clear, object-naming error rather than emit a bare identifier,
# silently drop the field, or fall back to the raw (semantic) query.
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_p2_unresolved_dimension_raises():
    """A dimension with no source column, no calc expression and no UDA has no
    physical mapping.  Phase 2 must raise ``SemanticBindingError`` naming the
    dimension instead of emitting a bare identifier (old Bug-893 fallback)."""
    cohort = _dim("cohort")  # no source_column_id / calc / UDA
    amount = _meas("amount", source_column_id="c-amount")
    bq = _bound(
        measures=[amount], dimensions=[cohort], grain=["cohort"],
        raw_query="SELECT cohort, SUM(amount) FROM sales GROUP BY cohort",
        select_expressions=[
            _se('cohort', classification="passthrough", inner_column="cohort"),
            _se('SUM(amount)', classification="analytical", agg_function="sum",
                inner_column="amount"),
        ],
    )
    db = _fact_db(dimensions=[cohort], measures=[amount])

    with pytest.raises(SemanticBindingError, match="cohort"):
        await _build_source_sql(bq, db, target_dialect="postgres")


@pytest.mark.asyncio
async def test_p2_unresolved_measure_raises():
    """A plain measure with no source column and no UDA has no physical
    mapping.  Phase 2 must raise ``SemanticBindingError`` naming the measure
    instead of silently dropping it from the SELECT list (measure twin of the
    Finding 2 dimension fallback)."""
    region = _dim("region", source_column_id="c-region")
    score = _meas("score")  # no source_column_id / UDA
    bq = _bound(
        measures=[score], dimensions=[region], grain=["region"],
        raw_query="SELECT region, SUM(score) FROM sales GROUP BY region",
        select_expressions=[
            _se('region', classification="passthrough", inner_column="region"),
            _se('SUM(score)', classification="analytical", agg_function="sum",
                inner_column="score"),
        ],
    )
    db = _fact_db(dimensions=[region], measures=[score])

    with pytest.raises(SemanticBindingError, match="score"):
        await _build_source_sql(bq, db, target_dialect="postgres")


# ---------------------------------------------------------------------------
# H15 / F-003-01 — raw ORDER BY preservation in the semantic source rewrite.
#
# When the parser flags has_unresolvable_order (an expression sort key), the
# rewriter must reconstruct the FULL raw ORDER BY (mapping semantic names to
# physical columns), NOT emit a phantom bare-column sort.
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_f_order_by_expression_preserved_not_phantom():
    """``ORDER BY LOWER(region) DESC`` must render the LOWER() expression over
    the physical column, never a bare ``"f"."region" DESC`` phantom sort."""
    region = _dim("region", source_column_id="c-region")
    amount = _meas("amount", source_column_id="c-amount")
    bq = _bound(
        measures=[amount], dimensions=[region], grain=["region"],
        order_by=[],  # parser cleared it
        has_unresolvable_order=True,
        raw_query=(
            "SELECT region, SUM(amount) FROM modelx GROUP BY region "
            "ORDER BY LOWER(region) DESC"
        ),
        select_expressions=[
            _se('region', classification="passthrough", inner_column="region"),
            _se('SUM(amount)', classification="analytical", agg_function="sum",
                inner_column="amount"),
        ],
    )
    db = _fact_db(dimensions=[region], measures=[amount])

    sql = await _build_source_sql(bq, db, target_dialect="postgres")

    upper = sql.upper()
    assert "ORDER BY" in upper
    assert "LOWER(" in upper, f"expression sort key dropped: {sql}"
    # The physical column must appear inside the LOWER() call — not as a bare
    # standalone ORDER BY column.
    assert '"f"."region"' in sql or '"region"' in sql
    order_clause = sql[upper.index("ORDER BY"):]
    assert "LOWER(" in order_clause.upper()
    _assert_self_parses(sql, "postgres")


@pytest.mark.asyncio
async def test_f_order_by_ratio_expression_preserved_with_limit():
    """``ORDER BY SUM(amount)/COUNT(*) DESC LIMIT 5`` must keep the ratio sort
    (so the top-5 are the right rows), not collapse to ``amount DESC``."""
    region = _dim("region", source_column_id="c-region")
    amount = _meas("amount", source_column_id="c-amount")
    bq = _bound(
        measures=[amount], dimensions=[region], grain=["region"],
        order_by=[], has_unresolvable_order=True, limit=5,
        raw_query=(
            "SELECT region, SUM(amount) FROM modelx GROUP BY region "
            "ORDER BY SUM(amount) / COUNT(*) DESC LIMIT 5"
        ),
        select_expressions=[
            _se('region', classification="passthrough", inner_column="region"),
            _se('SUM(amount)', classification="analytical", agg_function="sum",
                inner_column="amount"),
        ],
    )
    db = _fact_db(dimensions=[region], measures=[amount])

    sql = await _build_source_sql(bq, db, target_dialect="postgres")

    upper = sql.upper()
    order_clause = sql[upper.index("ORDER BY"):]
    assert "SUM(" in order_clause.upper() and "COUNT(" in order_clause.upper(), (
        f"ratio sort key not preserved: {sql}"
    )
    assert "LIMIT 5" in upper
    _assert_self_parses(sql, "postgres")


# ---------------------------------------------------------------------------
# Bug-1605 — persona-narrowed SELECT * with an EXPRESSION ORDER BY + LIMIT.
#
# ``_build_persona_star_sql`` previously dropped the unresolvable ORDER BY but
# kept the LIMIT unconditionally — returning an ARBITRARY top-N (a silent wrong
# result). The round-2 fix reconstructs the raw ORDER BY over the persona-allowed
# physical columns when EVERY referenced column is allowed (correct top-N), and
# otherwise suppresses the LIMIT so the result is never a silently-wrong top-N
# and never leaks a non-visible column.
# ---------------------------------------------------------------------------


def _persona_bound(*, dimensions, measures, raw_query, limit=None, offset=None):
    """Build a persona-narrowed ``SELECT *`` BoundQuery flagged
    ``has_unresolvable_order`` (an expression sort the parser could not
    represent as a bare column)."""
    bq = _bound(
        measures=list(measures), dimensions=list(dimensions),
        grain=[],
        order_by=[], has_unresolvable_order=True,
        limit=limit, offset=offset,
        select_star=True,
        raw_query=raw_query,
    )
    bq.persona_narrowed_star = True
    return bq


@pytest.mark.asyncio
async def test_persona_star_expr_order_allowed_cols_preserves_topn():
    """Persona-narrowed ``SELECT * ... ORDER BY LOWER(region) DESC LIMIT 5``
    where ``region`` IS persona-allowed: the LOWER() sort must be reconstructed
    over the physical column AND the LIMIT preserved (correct top-5)."""
    region = _dim("region", source_column_id="c-region")
    amount = _meas("amount", source_column_id="c-amount")
    bq = _persona_bound(
        dimensions=[region], measures=[amount], limit=5,
        raw_query=(
            "SELECT * FROM modelx ORDER BY LOWER(region) DESC LIMIT 5"
        ),
    )
    db = _fact_db(dimensions=[region], measures=[amount])

    sql = await _build_persona_star_sql(bq, db, "postgresql", "postgres")

    upper = sql.upper()
    assert "ORDER BY" in upper, f"expression sort dropped: {sql}"
    assert "LOWER(" in upper, f"expression sort key not preserved: {sql}"
    # The physical column appears inside the LOWER() call, not as a bare sort.
    assert '"region"' in sql
    # The LIMIT is correct now that the sort is honoured — it is the top-5.
    assert "LIMIT 5" in upper, f"LIMIT dropped despite a valid sort: {sql}"
    _assert_self_parses(sql, "postgres")


@pytest.mark.asyncio
async def test_persona_star_expr_order_excluded_col_suppresses_limit():
    """Persona-narrowed ``SELECT * ... ORDER BY LOWER(secret_code) DESC LIMIT 5``
    where ``secret_code`` is NOT persona-allowed (not in the resolved
    projection): the sort cannot be safely reproduced, so the LIMIT MUST be
    suppressed (no silently-wrong arbitrary top-5) and the excluded column MUST
    NOT leak into the SQL."""
    region = _dim("region", source_column_id="c-region")
    amount = _meas("amount", source_column_id="c-amount")
    bq = _persona_bound(
        dimensions=[region], measures=[amount], limit=5,
        raw_query=(
            "SELECT * FROM modelx ORDER BY LOWER(secret_code) DESC LIMIT 5"
        ),
    )
    db = _fact_db(dimensions=[region], measures=[amount])

    sql = await _build_persona_star_sql(bq, db, "postgresql", "postgres")

    upper = sql.upper()
    # The excluded column must never appear — no leak.
    assert "SECRET_CODE" not in upper, f"persona-excluded column leaked: {sql}"
    # The LIMIT must be suppressed — keeping it would return an arbitrary
    # (silently-wrong) top-5 because the sort could not be applied.
    assert "LIMIT" not in upper, (
        f"LIMIT kept without a usable sort -> silent wrong top-N: {sql}"
    )
    _assert_self_parses(sql, "postgres")


@pytest.mark.asyncio
async def test_persona_star_expr_order_excluded_col_suppresses_offset():
    """Same as above but with an OFFSET: an OFFSET over an unsorted set selects
    an arbitrary window, so it must be suppressed alongside the LIMIT."""
    region = _dim("region", source_column_id="c-region")
    amount = _meas("amount", source_column_id="c-amount")
    bq = _persona_bound(
        dimensions=[region], measures=[amount], limit=5, offset=10,
        raw_query=(
            "SELECT * FROM modelx ORDER BY LOWER(secret_code) DESC LIMIT 5 OFFSET 10"
        ),
    )
    db = _fact_db(dimensions=[region], measures=[amount])

    sql = await _build_persona_star_sql(bq, db, "postgresql", "postgres")

    upper = sql.upper()
    assert "SECRET_CODE" not in upper, f"persona-excluded column leaked: {sql}"
    assert "LIMIT" not in upper and "OFFSET" not in upper, (
        f"LIMIT/OFFSET kept without a usable sort: {sql}"
    )
    _assert_self_parses(sql, "postgres")


# ---------------------------------------------------------------------------
# Bug-4467 (AKA Bug-809): a persona/CLS-narrowed SELECT * with a WHERE / GROUP
# BY / ORDER BY on a JOINED-DIMENSION column previously fell back to a raw
# SELECT * via _substitute_table_names — which READS every physical column from
# the source (including the hidden/restricted ones the narrowing removed). The
# fix emits an EXPLICIT allowed-column projection spanning the base + joined
# relations, and rejects (403) when a clause references a non-allowed column.
# ---------------------------------------------------------------------------


def _persona_star_join_db():
    """Fact ``demo.sales`` (alias 'f') joined to dim ``demo.country`` (alias
    'd') on ``country_id = id``. The fact carries a HIDDEN ``secret_code``
    column that the persona narrowing removed — it must NEVER appear in the
    rendered SQL."""
    fact = _tbl("t-fact", "demo.sales", "f", table_type="fact")
    dimt = _tbl("t-dim", "demo.country", "d", table_type="dimension")
    cols = [
        _col("c-region", "t-fact", "region"),
        _col("c-amount", "t-fact", "amount", data_type="numeric"),
        _col("c-secret", "t-fact", "secret_code"),          # hidden / restricted
        _col("c-fkey", "t-fact", "country_id", data_type="integer"),
        _col("c-dkey", "t-dim", "id", data_type="integer"),
        _col("c-cname", "t-dim", "country_name"),
    ]
    join = types.SimpleNamespace(
        id="j-1", model_id=MODEL_ID,
        left_table_id="t-fact", left_column_id="c-fkey",
        right_table_id="t-dim", right_column_id="c-dkey",
        join_type="inner",
    )
    return FakeDB(tables=[fact, dimt], columns=cols, joins=[join])


def _persona_star_bound(*, dimensions, measures, raw_query, grain=None,
                        filters=None, order_by=None, limit=None,
                        has_unresolvable_order=False):
    bq = _bound(
        measures=list(measures), dimensions=list(dimensions),
        grain=grain if grain is not None else [],
        filters=filters or [], order_by=order_by or [],
        limit=limit, select_star=True, raw_query=raw_query,
        has_unresolvable_order=has_unresolvable_order,
    )
    bq.persona_narrowed_star = True
    return bq


@pytest.mark.asyncio
async def test_persona_star_where_on_joined_dim_explicit_projection():
    """WHERE on a persona-allowed JOINED-DIMENSION column: must emit an
    explicit allowed-column projection with the JOIN — NOT a raw SELECT * —
    and the hidden fact column must never appear."""
    region = _dim("region", source_column_id="c-region")
    country = _dim("country_name", source_column_id="c-cname")
    amount = _meas("amount", source_column_id="c-amount")
    bq = _persona_star_bound(
        dimensions=[region, country], measures=[amount],
        filters=[LogicalFilter("country_name", "eq", "France")],
        raw_query="SELECT * FROM modelx WHERE country_name = 'France'",
    )
    db = _persona_star_join_db()

    sql = await _build_persona_star_sql(bq, db, "postgresql", "postgres")
    upper = sql.upper()

    assert "SELECT *" not in upper, f"raw star fallback fired: {sql}"
    assert "SECRET_CODE" not in upper, f"hidden column leaked/read: {sql}"
    assert "JOIN" in upper, f"joined-dim column not joined: {sql}"
    # The allowed joined-dim column appears, explicitly qualified.
    assert '"country_name"' in sql, f"allowed joined column missing: {sql}"
    assert '"region"' in sql
    assert "FRANCE" in upper, f"WHERE on joined dim dropped: {sql}"
    _assert_self_parses(sql, "postgres")


@pytest.mark.asyncio
async def test_persona_star_group_by_joined_dim_explicit_projection():
    """GROUP BY on a persona-allowed joined-dimension column: explicit
    projection with the join, no raw SELECT *, no hidden column."""
    country = _dim("country_name", source_column_id="c-cname")
    amount = _meas("amount", source_column_id="c-amount")
    bq = _persona_star_bound(
        dimensions=[country], measures=[amount], grain=["country_name"],
        raw_query="SELECT * FROM modelx GROUP BY country_name",
    )
    db = _persona_star_join_db()

    sql = await _build_persona_star_sql(bq, db, "postgresql", "postgres")
    upper = sql.upper()

    assert "SELECT *" not in upper, f"raw star fallback fired: {sql}"
    assert "SECRET_CODE" not in upper, f"hidden column leaked/read: {sql}"
    assert "GROUP BY" in upper, f"GROUP BY dropped: {sql}"
    assert '"country_name"' in sql
    _assert_self_parses(sql, "postgres")


@pytest.mark.asyncio
async def test_persona_star_order_by_joined_dim_explicit_projection():
    """ORDER BY on a persona-allowed joined-dimension column: explicit
    projection, no raw SELECT *, no hidden column."""
    region = _dim("region", source_column_id="c-region")
    country = _dim("country_name", source_column_id="c-cname")
    amount = _meas("amount", source_column_id="c-amount")
    bq = _persona_star_bound(
        dimensions=[region, country], measures=[amount],
        order_by=[("country_name", "ASC")], limit=10,
        raw_query="SELECT * FROM modelx ORDER BY country_name LIMIT 10",
    )
    db = _persona_star_join_db()

    sql = await _build_persona_star_sql(bq, db, "postgresql", "postgres")
    upper = sql.upper()

    assert "SELECT *" not in upper, f"raw star fallback fired: {sql}"
    assert "SECRET_CODE" not in upper, f"hidden column leaked/read: {sql}"
    assert "ORDER BY" in upper and '"country_name"' in sql
    assert "LIMIT 10" in upper
    _assert_self_parses(sql, "postgres")


@pytest.mark.asyncio
async def test_cls_star_where_on_joined_dim_explicit_projection():
    """CLS narrowing (F-008-05) reuses _build_persona_star_sql, so it inherits
    the same fix: a CLS-narrowed SELECT * with a WHERE on an allowed joined
    column emits an explicit projection, never a raw SELECT *, and the
    restricted fact column is never read."""
    region = _dim("region", source_column_id="c-region")
    country = _dim("country_name", source_column_id="c-cname")
    amount = _meas("amount", source_column_id="c-amount")
    # CLS path sets persona_narrowed_star=True after dropping restricted
    # columns from the resolved lists — identical entry contract.
    bq = _persona_star_bound(
        dimensions=[region, country], measures=[amount],
        filters=[LogicalFilter("country_name", "eq", "Spain")],
        raw_query="SELECT * FROM modelx WHERE country_name = 'Spain'",
    )
    db = _persona_star_join_db()

    sql = await _build_persona_star_sql(bq, db, "postgresql", "postgres")
    upper = sql.upper()

    assert "SELECT *" not in upper, f"raw star fallback fired: {sql}"
    assert "SECRET_CODE" not in upper, f"restricted column leaked/read: {sql}"
    assert "JOIN" in upper and '"country_name"' in sql
    assert "SPAIN" in upper
    _assert_self_parses(sql, "postgres")


@pytest.mark.asyncio
async def test_persona_star_where_on_unallowed_column_rejects_403():
    """WHERE on a column the persona does NOT permit (not in the allowed
    projection): reject with 403 — never a raw SELECT * that would read it."""
    from fastapi import HTTPException

    region = _dim("region", source_column_id="c-region")
    amount = _meas("amount", source_column_id="c-amount")
    bq = _persona_star_bound(
        dimensions=[region], measures=[amount],
        filters=[LogicalFilter("secret_code", "eq", "X")],
        raw_query="SELECT * FROM modelx WHERE secret_code = 'X'",
    )
    db = _persona_star_join_db()

    with pytest.raises(HTTPException) as exc:
        await _build_persona_star_sql(bq, db, "postgresql", "postgres")
    assert exc.value.status_code == 403
    assert exc.value.detail["error_code"] == "COLUMN_RESTRICTED"


@pytest.mark.asyncio
async def test_persona_star_no_projectable_column_rejects_403():
    """When narrowing leaves no projectable allowed column at all, reject with
    403 rather than fall back to a raw SELECT * (Bug-4467/809)."""
    from fastapi import HTTPException

    # A dimension whose source column is not present in the model graph —
    # nothing projectable remains.
    orphan = _dim("ghost", source_column_id="c-missing")
    bq = _persona_star_bound(
        dimensions=[orphan], measures=[],
        raw_query="SELECT * FROM modelx",
    )
    db = _persona_star_join_db()

    with pytest.raises(HTTPException) as exc:
        await _build_persona_star_sql(bq, db, "postgresql", "postgres")
    assert exc.value.status_code == 403
    assert exc.value.detail["error_code"] == "COLUMN_RESTRICTED"


@pytest.mark.asyncio
async def test_non_narrowed_star_unchanged():
    """GUARDRAIL: the NON-narrowed SELECT * case (no persona/CLS restriction)
    does not enter _build_persona_star_sql at all — rewrite_for_source keeps
    the existing raw-star expansion path. persona_narrowed_star is False, so
    the explicit-projection builder is never invoked."""
    region = _dim("region", source_column_id="c-region")
    amount = _meas("amount", source_column_id="c-amount")
    bq = _bound(
        measures=[amount], dimensions=[region], grain=[],
        select_star=True,
        raw_query="SELECT * FROM modelx",
    )
    # No persona narrowing.
    assert getattr(bq, "persona_narrowed_star", False) is False
    db = _persona_star_join_db()

    sql = await rewrite_for_source(bq, db, target_dialect="postgres")
    # The non-narrowed path keeps SELECT * (table-name substituted).
    assert "*" in sql, f"non-narrowed star unexpectedly rewritten: {sql}"
    _assert_self_parses(sql, "postgres")
