/**
 * Shared docking contract for canvas relationships.
 *
 * The renderer (`CrowsFootEdge`) and the layout worker must resolve the *same*
 * border point, terminal heel and stored ratio for a relationship, otherwise a
 * route computed in the worker docks somewhere the renderer never draws it and
 * every "terminals match docking" check is meaningless.
 *
 * Existing renderer convention, which this module now owns:
 *   - `ratio` is the clamped anchor ratio along the chosen side.
 *   - parallel relationships add `offsetIndex`-based spacing on top of the
 *     stored base ratio (`ratioWithParallelOffset`), so the *stored* ratio must
 *     never already contain that offset.
 *   - the marker heel is `border + outward * markerExtent`, and persisted
 *     waypoints live strictly between the two heels.
 *
 * Pure functions only: no React, no engine imports, safe inside the worker.
 */
import type { AnchorSide, LayoutEdgeSnapshot, Point, Rect } from "./types";

export type MarkerKind = "many" | "one" | "optional" | "none";
export type RelationNotation = "crowsfoot" | "uml" | "diamond";

/** Parallel-relationship docking spacing. Mirrors the renderer exactly. */
export const PARALLEL_EDGE_SPACING = 15;
export const ANCHOR_RATIO_MIN = 0.08;
export const ANCHOR_RATIO_MAX = 0.92;

/**
 * Does this edge's saved docking bind layout and routing?
 *
 * Only genuine user intent and real locks keep saved docking: a locked route is
 * frozen by definition, a `straight` path is retained, and a `manual` route is
 * a docking the user authored. An `auto` route's saved sides/ratios were
 * generated by a *previous* Arrange, so the next explicit Arrange/Reroute must
 * be free to re-derive them — otherwise changing direction cannot re-orient the
 * diagram (F03).
 */
export function honoursSavedDocking(edge: LayoutEdgeSnapshot): boolean {
  return edge.locked || edge.pathMode === "straight" || edge.routeMode === "manual";
}

export function clampRatio(value: number, min = 0, max = 1): number {
  return Math.max(min, Math.min(max, value));
}

export function clampAnchorRatio(value: number): number {
  return clampRatio(value, ANCHOR_RATIO_MIN, ANCHOR_RATIO_MAX);
}

export function markerExtent(kind: MarkerKind, notation: RelationNotation): number {
  if (kind === "many") {
    if (notation === "uml") return 12;
    if (notation === "diamond") return 14;
    return 14;
  }
  if (kind === "one") return 8;
  if (kind === "optional") return 14;
  return 0;
}

export interface MarkerKindInput {
  sourceIsFact: boolean;
  targetIsFact: boolean;
  sourceIsDim?: boolean;
  targetIsDim?: boolean;
  /** User terminal override from the builder store; wins over the defaults. */
  override?: { source: string; target: string };
}

/**
 * Cardinality marker per endpoint. Extracted verbatim from the renderer so the
 * snapshot's marker extents cannot drift from the drawn markers.
 */
export function resolveMarkerKinds(input: MarkerKindInput): { source: MarkerKind; target: MarkerKind } {
  let source: MarkerKind = "none";
  let target: MarkerKind = "none";
  if (input.sourceIsFact && !input.targetIsFact) {
    source = "many";
    target = "one";
  } else if (!input.sourceIsFact && input.targetIsFact) {
    source = "one";
    target = "many";
  } else if (!input.sourceIsFact && !input.targetIsFact && input.sourceIsDim && input.targetIsDim) {
    // Dimension-to-dimension (snowflake / outrigger) edge (F-026-21). No fact
    // asymmetry to read, so default to the standard outrigger shape.
    source = "many";
    target = "one";
  }
  if (input.override) {
    source = input.override.source as MarkerKind;
    target = input.override.target as MarkerKind;
  }
  return { source, target };
}

export function outwardVector(side: AnchorSide): Point {
  if (side === "left") return { x: -1, y: 0 };
  if (side === "right") return { x: 1, y: 0 };
  if (side === "top") return { x: 0, y: -1 };
  return { x: 0, y: 1 };
}

export function oppositeSide(side: AnchorSide): AnchorSide {
  if (side === "left") return "right";
  if (side === "right") return "left";
  if (side === "top") return "bottom";
  return "top";
}

/** Side facing the other rectangle, derived from centres (renderer `autoSide`). */
/**
 * Which face of `source` a connector to `target` should leave through.
 *
 * The deltas are normalised by the SOURCE card's own half-extents, which makes
 * this the face a ray from the card's centre actually exits through. Comparing
 * raw |dx| against |dy| instead assumes cards are roughly square, and a
 * semantic model routinely contains a fact table with fifty columns: a card
 * two thousand pixels tall and three hundred wide.
 *
 * On such a card a dimension sitting to the RIGHT but above or below the
 * centre produced |dy| > |dx|, so the connector docked on the top or bottom
 * edge and then ran diagonally back across the full height of the card it had
 * just left. The relationship was drawn straight through its own fact table.
 *
 * For a square card the normalisation cancels and this is the previous
 * behaviour exactly, so ordinary diagrams are unaffected.
 */
/**
 * Where a connector should meet a card: the point at which the line between the
 * two card centres crosses this card's border.
 *
 * This is the whole docking rule, and it answers both questions at once — which
 * edge, and where along it — because they are the same question. The connector
 * leaves through the edge the two cards actually face each other across, at the
 * height the line between them is already travelling at. Nothing is ever docked
 * on the far side of a card, and nothing is dragged to the far END of an edge.
 *
 * Both deltas are measured against this card's OWN half-extents, which is what
 * makes it the true exit face. Comparing raw |dx| against |dy| instead assumes
 * cards are roughly square; a fact table with fifty columns is two thousand
 * pixels tall, and a dimension sitting to its right but above or below centre
 * was docked on the top or bottom edge, so the line ran diagonally back across
 * the full height of the card it had just left.
 *
 * For a square card the normalisation cancels, so ordinary diagrams keep the
 * behaviour they had.
 */
export function centreLineDocking(rect: Rect, other: Rect): { side: AnchorSide; ratio: number } {
  const cx = rect.x + rect.width / 2;
  const cy = rect.y + rect.height / 2;
  const dx = other.x + other.width / 2 - cx;
  const dy = other.y + other.height / 2 - cy;
  const halfWidth = rect.width > 0 ? rect.width / 2 : 1;
  const halfHeight = rect.height > 0 ? rect.height / 2 : 1;

  // Concentric cards have no line between their centres to intersect.
  if (dx === 0 && dy === 0) return { side: "right", ratio: 0.5 };

  if (Math.abs(dx) / halfWidth >= Math.abs(dy) / halfHeight) {
    // Leaves through a vertical edge: scale the centre line until it reaches
    // that edge, and read off the height it crosses at.
    const y = cy + dy * (halfWidth / Math.abs(dx));
    return {
      side: dx >= 0 ? "right" : "left",
      ratio: clampAnchorRatio(rect.height ? (y - rect.y) / rect.height : 0.5),
    };
  }
  const x = cx + dx * (halfHeight / Math.abs(dy));
  return {
    side: dy >= 0 ? "bottom" : "top",
    ratio: clampAnchorRatio(rect.width ? (x - rect.x) / rect.width : 0.5),
  };
}

export function sideFromCenters(source: Rect, target: Rect): AnchorSide {
  return centreLineDocking(source, target).side;
}

export function pointOnSide(rect: Rect, side: AnchorSide, ratio: number): Point {
  const r = clampRatio(ratio);
  if (side === "left") return { x: rect.x, y: rect.y + rect.height * r };
  if (side === "right") return { x: rect.x + rect.width, y: rect.y + rect.height * r };
  if (side === "top") return { x: rect.x + rect.width * r, y: rect.y };
  return { x: rect.x + rect.width * r, y: rect.y + rect.height };
}

/** Renderer parallel offset: `(index - (count-1)/2) * 15`. */
export function parallelOffsetFor(index: number, count: number): number {
  return (index - (count - 1) / 2) * PARALLEL_EDGE_SPACING;
}

export function ratioWithParallelOffset(rect: Rect, side: AnchorSide, ratio: number, parallelOffset: number): number {
  const span = side === "left" || side === "right" ? rect.height : rect.width;
  return clampAnchorRatio(ratio + (span ? parallelOffset / span : 0));
}

/** Base ratio pointing this side at `toward` (renderer `ratioToward`). */
export function sideRatioToward(rect: Rect, side: AnchorSide, toward: Point): number {
  if (side === "left" || side === "right") {
    return clampAnchorRatio(rect.height ? (toward.y - rect.y) / rect.height : 0.5);
  }
  return clampAnchorRatio(rect.width ? (toward.x - rect.x) / rect.width : 0.5);
}

/**
 * Ideal *base* anchor ratios for two opposing docks (no parallel offset baked
 * in — the caller re-applies it exactly like `ratioWithParallelOffset`).
 *
 * The rule is: find one coordinate both endpoints can actually reach, and put
 * both docks on it. That makes the connector a straight line with zero bends.
 * When no such coordinate exists, each dock points at the other card's centre,
 * which is the shortest dogleg.
 *
 * ## What "can actually reach" means, and why the obvious version is wrong
 *
 * A dock cannot sit anywhere on a card's edge: the anchor ratio is clamped to
 * [ANCHOR_RATIO_MIN, ANCHOR_RATIO_MAX] so a connector never attaches at the
 * very corner. The reachable span is therefore the card's **usable band**, not
 * its full edge.
 *
 * The previous version intersected the FULL edges, took the midpoint of that
 * intersection, and clamped each endpoint separately afterwards. With unequal
 * card heights the two clamps then pulled the endpoints to DIFFERENT
 * coordinates, producing a dogleg where a straight line was available:
 *
 *     source 420x640 at (0, 0), right side   -> y = 588.8
 *     target 180x160 at (700, 565), left side -> y = 602.5   (13.7 px apart)
 *
 * …while the usable bands overlap over [577.8, 588.8], so y = 583.3 was
 * reachable by both. Intersecting the usable bands first and choosing one
 * coordinate inside that intersection removes the disagreement by construction:
 * the value is reachable by both ends, so neither clamp moves it.
 *
 * ## Compatible sides
 *
 * Alignment only means anything when both docks vary along the SAME axis: two
 * vertical sides share a `y`, two horizontal sides share an `x`. A vertical
 * source with a horizontal target has no shared coordinate to agree on, so
 * that case falls back to pointing each dock at the other card's centre rather
 * than aligning on an axis only one of them moves along. The previous version
 * chose its axis from the source side alone and applied it to both.
 */
export function alignedSideRatios(
  sourceRect: Rect,
  sourceSide: AnchorSide,
  targetRect: Rect,
  targetSide: AnchorSide,
): { source: number; target: number } {
  // When the two cards do not face each other squarely, dock where the line
  // between their centres crosses this card's border.
  //
  // The previous fallback aimed each dock AT the other card's centre, which is
  // a different point and a much worse one on a tall card: a dimension well
  // above a fifty-column fact table produced a ratio outside 0..1, clamped to
  // the very top of the edge. That is the "far end of the card" behaviour —
  // the connector left from a corner instead of from beside the other card.
  const towardEachOther = {
    source: centreLineDocking(sourceRect, targetRect).side === sourceSide
      ? centreLineDocking(sourceRect, targetRect).ratio
      : sideRatioToward(sourceRect, sourceSide, centreOf(targetRect)),
    target: centreLineDocking(targetRect, sourceRect).side === targetSide
      ? centreLineDocking(targetRect, sourceRect).ratio
      : sideRatioToward(targetRect, targetSide, centreOf(sourceRect)),
  };

  const sourceVertical = sourceSide === "left" || sourceSide === "right";
  const targetVertical = targetSide === "left" || targetSide === "right";
  // Mixed axes have no coordinate both docks can agree on.
  if (sourceVertical !== targetVertical) return towardEachOther;

  const sourceBand = usableBand(sourceRect, sourceVertical);
  const targetBand = usableBand(targetRect, targetVertical);
  const low = Math.max(sourceBand.low, targetBand.low);
  const high = Math.min(sourceBand.high, targetBand.high);
  if (low > high) return towardEachOther;

  // Any coordinate in the intersection is reachable by both; the midpoint is
  // the one furthest from either card's clamp.
  const shared = (low + high) / 2;
  return {
    source: ratioForCoordinate(sourceRect, sourceVertical, shared),
    target: ratioForCoordinate(targetRect, targetVertical, shared),
  };
}

function centreOf(rect: Rect): Point {
  return { x: rect.x + rect.width / 2, y: rect.y + rect.height / 2 };
}

/** The span of a side a dock can actually occupy, after the anchor clamp. */
function usableBand(rect: Rect, vertical: boolean): { low: number; high: number } {
  const origin = vertical ? rect.y : rect.x;
  const span = vertical ? rect.height : rect.width;
  return { low: origin + span * ANCHOR_RATIO_MIN, high: origin + span * ANCHOR_RATIO_MAX };
}

/** Ratio that puts this card's dock at an absolute coordinate on its side. */
function ratioForCoordinate(rect: Rect, vertical: boolean, coordinate: number): number {
  const origin = vertical ? rect.y : rect.x;
  const span = vertical ? rect.height : rect.width;
  return clampAnchorRatio(span ? (coordinate - origin) / span : 0.5);
}

export interface Docking {
  side: AnchorSide;
  /** Effective ratio used for geometry; already includes the parallel offset. */
  ratio: number;
  /** Base ratio that must be persisted so the renderer reproduces `heel`. */
  baseRatio: number;
  /** Point on the card border. */
  border: Point;
  /** Marker heel: border pushed outwards by the marker extent. */
  heel: Point;
}

export interface DockingInput {
  rect: Rect;
  side: AnchorSide;
  /** Persisted base ratio, absent for an auto-docked endpoint. */
  baseRatio?: number | null;
  /** Centre of the opposite endpoint, used when no ratio is persisted. */
  toward: Point;
  offsetIndex?: number;
  totalEdges?: number;
  markerExtent: number;
}

/**
 * Resolve one endpoint's border point, heel and persistable base ratio.
 *
 * The returned `ratio` is what the geometry validator and the router use; the
 * returned `baseRatio` is what the canvas must store so that the renderer, which
 * re-applies the parallel offset itself, lands on the same heel.
 */
export function resolveDocking(input: DockingInput): Docking {
  const { rect, side } = input;
  const baseRatio = input.baseRatio === null || input.baseRatio === undefined
    ? sideRatioToward(rect, side, input.toward)
    : clampAnchorRatio(input.baseRatio);
  const offset = parallelOffsetFor(input.offsetIndex ?? 0, input.totalEdges ?? 1);
  const ratio = ratioWithParallelOffset(rect, side, baseRatio, offset);
  const border = pointOnSide(rect, side, ratio);
  const vector = outwardVector(side);
  return {
    side,
    ratio,
    baseRatio,
    border,
    heel: { x: border.x + vector.x * input.markerExtent, y: border.y + vector.y * input.markerExtent },
  };
}

/**
 * Inverse of the renderer's parallel offset: the base ratio to persist so that
 * `ratioWithParallelOffset` reproduces `effectiveRatio` exactly.
 *
 * Returns `null` when no persistable base ratio exists (the effective ratio
 * falls outside the anchor clamps), which callers must treat as an explicit
 * failure rather than persisting a ratio the renderer would draw elsewhere.
 */
/**
 * The base ratio to persist for an attachment the user dragged to a point.
 *
 * The pointer calculation yields an EFFECTIVE ratio — where on the card border
 * the heel actually sits. The persisted convention is a BASE ratio, to which
 * the renderer adds the parallel fan-out offset for this edge. Storing the
 * effective value as if it were the base makes the renderer add the offset a
 * second time, so the attachment lands beside where the user dropped it: on the
 * second of two parallel joins, a drop asking for y=120 rendered at y=127.5.
 *
 * Unlike `deriveBaseRatio`, this never refuses. The user dropped somewhere; if
 * the fan-out means that exact point is not reachable, the nearest reachable
 * one is the honest answer. `deriveBaseRatio` keeps its veto because it is
 * checking an engine's claim, where a mismatch is a real error.
 */
export function baseRatioForDroppedPoint(
  rect: Rect,
  side: AnchorSide,
  effectiveRatio: number,
  offsetIndex?: number,
  totalEdges?: number,
): number {
  const span = side === "left" || side === "right" ? rect.height : rect.width;
  const offset = parallelOffsetFor(offsetIndex ?? 0, totalEdges ?? 1);
  return clampAnchorRatio(effectiveRatio - (span ? offset / span : 0));
}

export function deriveBaseRatio(
  rect: Rect,
  side: AnchorSide,
  effectiveRatio: number,
  offsetIndex?: number,
  totalEdges?: number,
): number | null {
  const span = side === "left" || side === "right" ? rect.height : rect.width;
  const offset = parallelOffsetFor(offsetIndex ?? 0, totalEdges ?? 1);
  const base = clampAnchorRatio(effectiveRatio - (span ? offset / span : 0));
  const roundTrip = ratioWithParallelOffset(rect, side, base, offset);
  return Math.abs(roundTrip - effectiveRatio) <= 1e-6 ? base : null;
}

/**
 * Adopt an engine-produced endpoint as the route terminal.
 *
 * libavoid may *nudge* a connection point along the card side — it spreads
 * connectors that share a docking point. Splicing the originally requested heel
 * back onto its polyline would leave a small diagonal stub, so the engine's
 * point is adopted and its persisted base ratio is derived from where the
 * engine actually docked.
 *
 * A point that left its intended side, or that sits at the wrong distance from
 * the border (wrong marker extent), is rejected with an explicit failure: the
 * renderer could not draw it.
 */
export function adoptRoutedEndpoint(input: {
  point: Point;
  rect: Rect;
  side: AnchorSide;
  extent: number;
  offsetIndex?: number;
  totalEdges?: number;
  /**
   * How far a router terminal may drift from its assigned dock before the route is
   * rejected. Within the bound the terminal is corrected onto the dock; beyond it
   * the router docked somewhere else and the route is refused.
   */
  driftLimit?: number;
  /** Identifies the relationship in a rejection; purely diagnostic. */
  label?: string;
  /** The terminal the caller asked the router for; purely diagnostic. */
  assigned?: Point;
}): { heel: Point; baseRatio: number; corrected: boolean } {
  const { point, rect, side, extent } = input;
  const limit = input.driftLimit ?? 0.5;
  const vertical = side === "left" || side === "right";
  // The border the renderer will draw at, and the side's span, so a terminal that
  // docked on a different side can be told apart from one nudged along the normal.
  const border =
    side === "right" ? rect.x + rect.width + extent
    : side === "left" ? rect.x - extent
    : side === "top" ? rect.y - extent
    : rect.y + rect.height + extent;
  const span = vertical ? rect.height : rect.width;
  const along = (vertical ? point.y - rect.y : point.x - rect.x);
  const normalDistance = vertical ? Math.abs(point.x - border) : Math.abs(point.y - border);
  if (
    !Number.isFinite(along) ||
    along < -limit ||
    along > span + limit ||
    normalDistance > limit
  ) {
    const expected =
      side === "right" ? rect.x + rect.width + extent
      : side === "left" ? rect.x - extent
      : side === "top" ? rect.y - extent
      : rect.y + rect.height + extent;
    const assigned = input.assigned;
    // Distinguish "the router moved it" from "we expected the wrong border": the
    // two have different fixes and the message must not make the reader guess.
    const movedBy = assigned
      ? ` routerMovedBy=${Math.hypot(point.x - assigned.x, point.y - assigned.y).toFixed(2)}`
      : " assigned=unknown";
    throw new Error(
      `layout engine moved a relationship terminal off its docking side ` +
        `[edge=${input.label ?? "unknown"} side=${side} ` +
        `point=(${point.x.toFixed(1)},${point.y.toFixed(1)}) ` +
        `expectedBorder=${expected.toFixed(1)} ` +
        `rect=(${rect.x.toFixed(1)},${rect.y.toFixed(1)},${rect.width.toFixed(1)}x${rect.height.toFixed(1)}) ` +
        `extent=${extent} offset=${input.offsetIndex ?? 0}/${input.totalEdges ?? 1} ` +
        `offBy=${normalDistance.toFixed(2)}${movedBy}` +
        (assigned ? ` assigned=(${assigned.x.toFixed(1)},${assigned.y.toFixed(1)})` : "") +
        `]`,
    );
  }
  // Correct the normal coordinate onto the dock the renderer draws; keep the
  // router's along-side coordinate, which is the part it legitimately adopts.
  const heel: Point = vertical
    ? { x: border, y: rect.y + along }
    : { x: rect.x + along, y: border };
  const ratio = span ? along / span : 0.5;
  const baseRatio = deriveBaseRatio(rect, side, ratio, input.offsetIndex, input.totalEdges);
  if (baseRatio === null) {
    throw new Error("layout engine docked a relationship at an unsupported anchor ratio");
  }
  return {
    heel,
    baseRatio,
    corrected: Math.hypot(point.x - heel.x, point.y - heel.y) > 1e-6,
  };
}
