/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 126
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 81
#define ALIAS_COUNT 0
#define TOKEN_COUNT 41
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 7
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  aux_sym_drillthrough_statement_token1 = 2,
  aux_sym_maxrows_clause_token1 = 3,
  aux_sym_return_clause_token1 = 4,
  anon_sym_COMMA = 5,
  aux_sym_with_clause_token1 = 6,
  aux_sym_with_member_def_token1 = 7,
  aux_sym_with_member_def_token2 = 8,
  aux_sym_with_set_def_token1 = 9,
  anon_sym_EQ = 10,
  anon_sym_LPAREN = 11,
  anon_sym_RPAREN = 12,
  anon_sym_PLUS = 13,
  anon_sym_DASH = 14,
  anon_sym_STAR = 15,
  anon_sym_SLASH = 16,
  anon_sym_LT_GT = 17,
  anon_sym_LT = 18,
  anon_sym_GT = 19,
  anon_sym_LT_EQ = 20,
  anon_sym_GT_EQ = 21,
  aux_sym_select_statement_token1 = 22,
  aux_sym_select_statement_token2 = 23,
  aux_sym_axis_def_token1 = 24,
  aux_sym_axis_def_token2 = 25,
  aux_sym_axis_def_token3 = 26,
  aux_sym_axis_id_token1 = 27,
  aux_sym_axis_id_token2 = 28,
  aux_sym_axis_id_token3 = 29,
  anon_sym_LBRACE = 30,
  anon_sym_COLON = 31,
  anon_sym_RBRACE = 32,
  aux_sym_dim_properties_token1 = 33,
  aux_sym_dim_properties_token2 = 34,
  aux_sym_where_clause_token1 = 35,
  anon_sym_DOT = 36,
  anon_sym_AMP = 37,
  sym_bracket_name = 38,
  sym_number = 39,
  sym_string_literal = 40,
  sym_source_file = 41,
  sym_mdx_statement = 42,
  sym_drillthrough_statement = 43,
  sym_maxrows_clause = 44,
  sym_return_clause = 45,
  sym_return_column = 46,
  sym_with_clause = 47,
  sym_with_member_def = 48,
  sym_with_set_def = 49,
  sym_member_property = 50,
  sym_calc_expression = 51,
  sym_calc_atom = 52,
  sym_calc_paren = 53,
  sym_operator = 54,
  sym_select_statement = 55,
  sym_axis_list = 56,
  sym_axis_def = 57,
  sym_axis_id = 58,
  sym_axis_body = 59,
  sym_axis_token = 60,
  sym_func_call = 61,
  sym_set_literal = 62,
  sym_dim_properties = 63,
  sym_from_clause = 64,
  sym_subselect = 65,
  sym_where_clause = 66,
  sym_where_tuple = 67,
  sym_dotted_ref = 68,
  sym_ampersand_key = 69,
  aux_sym_return_clause_repeat1 = 70,
  aux_sym_with_clause_repeat1 = 71,
  aux_sym_with_member_def_repeat1 = 72,
  aux_sym_calc_expression_repeat1 = 73,
  aux_sym_axis_list_repeat1 = 74,
  aux_sym_axis_body_repeat1 = 75,
  aux_sym_func_call_repeat1 = 76,
  aux_sym_set_literal_repeat1 = 77,
  aux_sym_dim_properties_repeat1 = 78,
  aux_sym_where_tuple_repeat1 = 79,
  aux_sym_dotted_ref_repeat1 = 80,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [aux_sym_drillthrough_statement_token1] = "drillthrough_statement_token1",
  [aux_sym_maxrows_clause_token1] = "maxrows_clause_token1",
  [aux_sym_return_clause_token1] = "return_clause_token1",
  [anon_sym_COMMA] = ",",
  [aux_sym_with_clause_token1] = "with_clause_token1",
  [aux_sym_with_member_def_token1] = "with_member_def_token1",
  [aux_sym_with_member_def_token2] = "with_member_def_token2",
  [aux_sym_with_set_def_token1] = "with_set_def_token1",
  [anon_sym_EQ] = "=",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_LT_GT] = "<>",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [aux_sym_select_statement_token1] = "select_statement_token1",
  [aux_sym_select_statement_token2] = "select_statement_token2",
  [aux_sym_axis_def_token1] = "axis_def_token1",
  [aux_sym_axis_def_token2] = "axis_def_token2",
  [aux_sym_axis_def_token3] = "axis_def_token3",
  [aux_sym_axis_id_token1] = "axis_id_token1",
  [aux_sym_axis_id_token2] = "axis_id_token2",
  [aux_sym_axis_id_token3] = "axis_id_token3",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COLON] = ":",
  [anon_sym_RBRACE] = "}",
  [aux_sym_dim_properties_token1] = "dim_properties_token1",
  [aux_sym_dim_properties_token2] = "dim_properties_token2",
  [aux_sym_where_clause_token1] = "where_clause_token1",
  [anon_sym_DOT] = ".",
  [anon_sym_AMP] = "&",
  [sym_bracket_name] = "bracket_name",
  [sym_number] = "number",
  [sym_string_literal] = "string_literal",
  [sym_source_file] = "source_file",
  [sym_mdx_statement] = "mdx_statement",
  [sym_drillthrough_statement] = "drillthrough_statement",
  [sym_maxrows_clause] = "maxrows_clause",
  [sym_return_clause] = "return_clause",
  [sym_return_column] = "return_column",
  [sym_with_clause] = "with_clause",
  [sym_with_member_def] = "with_member_def",
  [sym_with_set_def] = "with_set_def",
  [sym_member_property] = "member_property",
  [sym_calc_expression] = "calc_expression",
  [sym_calc_atom] = "calc_atom",
  [sym_calc_paren] = "calc_paren",
  [sym_operator] = "operator",
  [sym_select_statement] = "select_statement",
  [sym_axis_list] = "axis_list",
  [sym_axis_def] = "axis_def",
  [sym_axis_id] = "axis_id",
  [sym_axis_body] = "axis_body",
  [sym_axis_token] = "axis_token",
  [sym_func_call] = "func_call",
  [sym_set_literal] = "set_literal",
  [sym_dim_properties] = "dim_properties",
  [sym_from_clause] = "from_clause",
  [sym_subselect] = "subselect",
  [sym_where_clause] = "where_clause",
  [sym_where_tuple] = "where_tuple",
  [sym_dotted_ref] = "dotted_ref",
  [sym_ampersand_key] = "ampersand_key",
  [aux_sym_return_clause_repeat1] = "return_clause_repeat1",
  [aux_sym_with_clause_repeat1] = "with_clause_repeat1",
  [aux_sym_with_member_def_repeat1] = "with_member_def_repeat1",
  [aux_sym_calc_expression_repeat1] = "calc_expression_repeat1",
  [aux_sym_axis_list_repeat1] = "axis_list_repeat1",
  [aux_sym_axis_body_repeat1] = "axis_body_repeat1",
  [aux_sym_func_call_repeat1] = "func_call_repeat1",
  [aux_sym_set_literal_repeat1] = "set_literal_repeat1",
  [aux_sym_dim_properties_repeat1] = "dim_properties_repeat1",
  [aux_sym_where_tuple_repeat1] = "where_tuple_repeat1",
  [aux_sym_dotted_ref_repeat1] = "dotted_ref_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [aux_sym_drillthrough_statement_token1] = aux_sym_drillthrough_statement_token1,
  [aux_sym_maxrows_clause_token1] = aux_sym_maxrows_clause_token1,
  [aux_sym_return_clause_token1] = aux_sym_return_clause_token1,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [aux_sym_with_clause_token1] = aux_sym_with_clause_token1,
  [aux_sym_with_member_def_token1] = aux_sym_with_member_def_token1,
  [aux_sym_with_member_def_token2] = aux_sym_with_member_def_token2,
  [aux_sym_with_set_def_token1] = aux_sym_with_set_def_token1,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_LT_GT] = anon_sym_LT_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [aux_sym_select_statement_token1] = aux_sym_select_statement_token1,
  [aux_sym_select_statement_token2] = aux_sym_select_statement_token2,
  [aux_sym_axis_def_token1] = aux_sym_axis_def_token1,
  [aux_sym_axis_def_token2] = aux_sym_axis_def_token2,
  [aux_sym_axis_def_token3] = aux_sym_axis_def_token3,
  [aux_sym_axis_id_token1] = aux_sym_axis_id_token1,
  [aux_sym_axis_id_token2] = aux_sym_axis_id_token2,
  [aux_sym_axis_id_token3] = aux_sym_axis_id_token3,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [aux_sym_dim_properties_token1] = aux_sym_dim_properties_token1,
  [aux_sym_dim_properties_token2] = aux_sym_dim_properties_token2,
  [aux_sym_where_clause_token1] = aux_sym_where_clause_token1,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_AMP] = anon_sym_AMP,
  [sym_bracket_name] = sym_bracket_name,
  [sym_number] = sym_number,
  [sym_string_literal] = sym_string_literal,
  [sym_source_file] = sym_source_file,
  [sym_mdx_statement] = sym_mdx_statement,
  [sym_drillthrough_statement] = sym_drillthrough_statement,
  [sym_maxrows_clause] = sym_maxrows_clause,
  [sym_return_clause] = sym_return_clause,
  [sym_return_column] = sym_return_column,
  [sym_with_clause] = sym_with_clause,
  [sym_with_member_def] = sym_with_member_def,
  [sym_with_set_def] = sym_with_set_def,
  [sym_member_property] = sym_member_property,
  [sym_calc_expression] = sym_calc_expression,
  [sym_calc_atom] = sym_calc_atom,
  [sym_calc_paren] = sym_calc_paren,
  [sym_operator] = sym_operator,
  [sym_select_statement] = sym_select_statement,
  [sym_axis_list] = sym_axis_list,
  [sym_axis_def] = sym_axis_def,
  [sym_axis_id] = sym_axis_id,
  [sym_axis_body] = sym_axis_body,
  [sym_axis_token] = sym_axis_token,
  [sym_func_call] = sym_func_call,
  [sym_set_literal] = sym_set_literal,
  [sym_dim_properties] = sym_dim_properties,
  [sym_from_clause] = sym_from_clause,
  [sym_subselect] = sym_subselect,
  [sym_where_clause] = sym_where_clause,
  [sym_where_tuple] = sym_where_tuple,
  [sym_dotted_ref] = sym_dotted_ref,
  [sym_ampersand_key] = sym_ampersand_key,
  [aux_sym_return_clause_repeat1] = aux_sym_return_clause_repeat1,
  [aux_sym_with_clause_repeat1] = aux_sym_with_clause_repeat1,
  [aux_sym_with_member_def_repeat1] = aux_sym_with_member_def_repeat1,
  [aux_sym_calc_expression_repeat1] = aux_sym_calc_expression_repeat1,
  [aux_sym_axis_list_repeat1] = aux_sym_axis_list_repeat1,
  [aux_sym_axis_body_repeat1] = aux_sym_axis_body_repeat1,
  [aux_sym_func_call_repeat1] = aux_sym_func_call_repeat1,
  [aux_sym_set_literal_repeat1] = aux_sym_set_literal_repeat1,
  [aux_sym_dim_properties_repeat1] = aux_sym_dim_properties_repeat1,
  [aux_sym_where_tuple_repeat1] = aux_sym_where_tuple_repeat1,
  [aux_sym_dotted_ref_repeat1] = aux_sym_dotted_ref_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_drillthrough_statement_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_maxrows_clause_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_return_clause_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_with_clause_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_with_member_def_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_with_member_def_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_with_set_def_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_select_statement_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_select_statement_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_axis_def_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_axis_def_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_axis_def_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_axis_id_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_axis_id_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_axis_id_token3] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_dim_properties_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dim_properties_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_where_clause_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [sym_bracket_name] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_mdx_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_drillthrough_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_maxrows_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_return_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_return_column] = {
    .visible = true,
    .named = true,
  },
  [sym_with_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_with_member_def] = {
    .visible = true,
    .named = true,
  },
  [sym_with_set_def] = {
    .visible = true,
    .named = true,
  },
  [sym_member_property] = {
    .visible = true,
    .named = true,
  },
  [sym_calc_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_calc_atom] = {
    .visible = true,
    .named = true,
  },
  [sym_calc_paren] = {
    .visible = true,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_select_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_axis_list] = {
    .visible = true,
    .named = true,
  },
  [sym_axis_def] = {
    .visible = true,
    .named = true,
  },
  [sym_axis_id] = {
    .visible = true,
    .named = true,
  },
  [sym_axis_body] = {
    .visible = true,
    .named = true,
  },
  [sym_axis_token] = {
    .visible = true,
    .named = true,
  },
  [sym_func_call] = {
    .visible = true,
    .named = true,
  },
  [sym_set_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_dim_properties] = {
    .visible = true,
    .named = true,
  },
  [sym_from_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_subselect] = {
    .visible = true,
    .named = true,
  },
  [sym_where_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_where_tuple] = {
    .visible = true,
    .named = true,
  },
  [sym_dotted_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_ampersand_key] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_return_clause_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_with_clause_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_with_member_def_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_calc_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_axis_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_axis_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_func_call_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_set_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dim_properties_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_where_tuple_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dotted_ref_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_axis_name = 1,
  field_body = 2,
  field_count = 3,
  field_expression = 4,
  field_name = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_axis_name] = "axis_name",
  [field_body] = "body",
  [field_count] = "count",
  [field_expression] = "expression",
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 2},
  [5] = {.index = 7, .length = 2},
  [6] = {.index = 9, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_count, 1},
  [1] =
    {field_axis_name, 2},
    {field_body, 0},
  [3] =
    {field_expression, 3},
    {field_name, 1},
  [5] =
    {field_axis_name, 3},
    {field_body, 0},
  [7] =
    {field_axis_name, 4},
    {field_body, 2},
  [9] =
    {field_axis_name, 5},
    {field_body, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 8,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 4,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 2,
  [42] = 42,
  [43] = 3,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 5,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 51,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 6,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 112,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      ADVANCE_MAP(
        '"', 2,
        '&', 26,
        '(', 9,
        ')', 10,
        '*', 13,
        '+', 11,
        ',', 7,
        '-', 12,
        '.', 25,
        '/', 14,
        ':', 23,
        '<', 16,
        '=', 8,
        '>', 17,
        '[', 3,
        '{', 22,
        '}', 24,
        '0', 21,
        '1', 21,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('2' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 2,
        '&', 26,
        '(', 9,
        ')', 10,
        '*', 13,
        '+', 11,
        ',', 7,
        '-', 12,
        '.', 25,
        '/', 14,
        ':', 23,
        '<', 16,
        '=', 8,
        '>', 17,
        '[', 3,
        '{', 22,
        '}', 24,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(31);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == ']') ADVANCE(27);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 5:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LT_GT);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(18);
      if (lookahead == '>') ADVANCE(15);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(19);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_axis_id_token3);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_axis_id_token3);
      if (lookahead == '.') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_bracket_name);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'A', 1,
        'a', 1,
        'C', 2,
        'c', 2,
        'D', 3,
        'd', 3,
        'E', 4,
        'e', 4,
        'F', 5,
        'f', 5,
        'M', 6,
        'm', 6,
        'N', 7,
        'n', 7,
        'O', 8,
        'o', 8,
        'P', 9,
        'p', 9,
        'R', 10,
        'r', 10,
        'S', 11,
        's', 11,
        'W', 12,
        'w', 12,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(13);
      END_STATE();
    case 2:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(14);
      END_STATE();
    case 3:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(15);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(16);
      END_STATE();
    case 4:
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(17);
      END_STATE();
    case 5:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 6:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(19);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 7:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 8:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(22);
      END_STATE();
    case 9:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 10:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(24);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(25);
      END_STATE();
    case 11:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 12:
      if (lookahead == 'H' ||
          lookahead == 'h') ADVANCE(27);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(28);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_with_member_def_token2);
      END_STATE();
    case 14:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(29);
      END_STATE();
    case 15:
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(30);
      END_STATE();
    case 16:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(31);
      END_STATE();
    case 17:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(32);
      END_STATE();
    case 18:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(33);
      END_STATE();
    case 19:
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(34);
      END_STATE();
    case 20:
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(35);
      END_STATE();
    case 21:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(36);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_axis_def_token3);
      END_STATE();
    case 23:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(37);
      END_STATE();
    case 24:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(38);
      END_STATE();
    case 25:
      if (lookahead == 'W' ||
          lookahead == 'w') ADVANCE(39);
      END_STATE();
    case 26:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(40);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(41);
      END_STATE();
    case 27:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(42);
      END_STATE();
    case 28:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(43);
      END_STATE();
    case 29:
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(44);
      END_STATE();
    case 30:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 31:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(46);
      END_STATE();
    case 32:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(47);
      END_STATE();
    case 33:
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(48);
      END_STATE();
    case 34:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(49);
      END_STATE();
    case 35:
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(50);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_axis_def_token1);
      END_STATE();
    case 37:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(51);
      END_STATE();
    case 38:
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(52);
      END_STATE();
    case 39:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(53);
      END_STATE();
    case 40:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(54);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_with_set_def_token1);
      END_STATE();
    case 42:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(55);
      END_STATE();
    case 43:
      if (lookahead == 'H' ||
          lookahead == 'h') ADVANCE(56);
      END_STATE();
    case 44:
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(57);
      END_STATE();
    case 45:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(58);
      END_STATE();
    case 46:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(59);
      END_STATE();
    case 47:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(60);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_select_statement_token2);
      END_STATE();
    case 49:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(61);
      END_STATE();
    case 50:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(62);
      END_STATE();
    case 51:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(63);
      END_STATE();
    case 52:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(64);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_axis_id_token2);
      END_STATE();
    case 54:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(65);
      END_STATE();
    case 55:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(66);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_with_clause_token1);
      END_STATE();
    case 57:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(67);
      END_STATE();
    case 58:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(68);
      END_STATE();
    case 59:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(69);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_axis_def_token2);
      END_STATE();
    case 61:
      if (lookahead == 'W' ||
          lookahead == 'w') ADVANCE(70);
      END_STATE();
    case 62:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(71);
      END_STATE();
    case 63:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(72);
      END_STATE();
    case 64:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(73);
      END_STATE();
    case 65:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(74);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_where_clause_token1);
      END_STATE();
    case 67:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(75);
      END_STATE();
    case 68:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(76);
      END_STATE();
    case 69:
      if (lookahead == 'H' ||
          lookahead == 'h') ADVANCE(77);
      END_STATE();
    case 70:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(78);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym_with_member_def_token1);
      END_STATE();
    case 72:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(79);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_return_clause_token1);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym_select_statement_token1);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym_axis_id_token1);
      END_STATE();
    case 76:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(80);
      END_STATE();
    case 77:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(81);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_maxrows_clause_token1);
      END_STATE();
    case 79:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(82);
      END_STATE();
    case 80:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(83);
      END_STATE();
    case 81:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(84);
      END_STATE();
    case 82:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(85);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(aux_sym_dim_properties_token1);
      END_STATE();
    case 84:
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(86);
      END_STATE();
    case 85:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(87);
      END_STATE();
    case 86:
      if (lookahead == 'G' ||
          lookahead == 'g') ADVANCE(88);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(aux_sym_dim_properties_token2);
      END_STATE();
    case 88:
      if (lookahead == 'H' ||
          lookahead == 'h') ADVANCE(89);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(aux_sym_drillthrough_statement_token1);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 4},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 4},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 4},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 4},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 1},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [aux_sym_drillthrough_statement_token1] = ACTIONS(1),
    [aux_sym_maxrows_clause_token1] = ACTIONS(1),
    [aux_sym_return_clause_token1] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [aux_sym_with_clause_token1] = ACTIONS(1),
    [aux_sym_with_member_def_token1] = ACTIONS(1),
    [aux_sym_with_member_def_token2] = ACTIONS(1),
    [aux_sym_with_set_def_token1] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_LT_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [aux_sym_select_statement_token1] = ACTIONS(1),
    [aux_sym_select_statement_token2] = ACTIONS(1),
    [aux_sym_axis_def_token1] = ACTIONS(1),
    [aux_sym_axis_def_token2] = ACTIONS(1),
    [aux_sym_axis_def_token3] = ACTIONS(1),
    [aux_sym_axis_id_token1] = ACTIONS(1),
    [aux_sym_axis_id_token2] = ACTIONS(1),
    [aux_sym_axis_id_token3] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [aux_sym_dim_properties_token1] = ACTIONS(1),
    [aux_sym_dim_properties_token2] = ACTIONS(1),
    [aux_sym_where_clause_token1] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [sym_bracket_name] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(109),
    [sym_mdx_statement] = STATE(121),
    [sym_drillthrough_statement] = STATE(121),
    [sym_with_clause] = STATE(106),
    [sym_select_statement] = STATE(120),
    [aux_sym_drillthrough_statement_token1] = ACTIONS(3),
    [aux_sym_with_clause_token1] = ACTIONS(5),
    [aux_sym_select_statement_token1] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(13), 1,
      anon_sym_DOT,
    ACTIONS(15), 1,
      anon_sym_AMP,
    STATE(3), 2,
      sym_ampersand_key,
      aux_sym_dotted_ref_repeat1,
    ACTIONS(9), 10,
      aux_sym_with_member_def_token1,
      aux_sym_with_member_def_token2,
      aux_sym_with_set_def_token1,
      anon_sym_DASH,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_select_statement_token1,
      aux_sym_axis_def_token3,
      aux_sym_dim_properties_token1,
      sym_identifier,
    ACTIONS(11), 16,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_LBRACE,
      anon_sym_COLON,
      anon_sym_RBRACE,
      sym_bracket_name,
      sym_number,
      sym_string_literal,
  [41] = 5,
    ACTIONS(13), 1,
      anon_sym_DOT,
    ACTIONS(15), 1,
      anon_sym_AMP,
    STATE(4), 2,
      sym_ampersand_key,
      aux_sym_dotted_ref_repeat1,
    ACTIONS(17), 10,
      aux_sym_with_member_def_token1,
      aux_sym_with_member_def_token2,
      aux_sym_with_set_def_token1,
      anon_sym_DASH,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_select_statement_token1,
      aux_sym_axis_def_token3,
      aux_sym_dim_properties_token1,
      sym_identifier,
    ACTIONS(19), 16,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_LBRACE,
      anon_sym_COLON,
      anon_sym_RBRACE,
      sym_bracket_name,
      sym_number,
      sym_string_literal,
  [82] = 5,
    ACTIONS(25), 1,
      anon_sym_DOT,
    ACTIONS(28), 1,
      anon_sym_AMP,
    STATE(4), 2,
      sym_ampersand_key,
      aux_sym_dotted_ref_repeat1,
    ACTIONS(21), 10,
      aux_sym_with_member_def_token1,
      aux_sym_with_member_def_token2,
      aux_sym_with_set_def_token1,
      anon_sym_DASH,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_select_statement_token1,
      aux_sym_axis_def_token3,
      aux_sym_dim_properties_token1,
      sym_identifier,
    ACTIONS(23), 16,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_LBRACE,
      anon_sym_COLON,
      anon_sym_RBRACE,
      sym_bracket_name,
      sym_number,
      sym_string_literal,
  [123] = 2,
    ACTIONS(31), 10,
      aux_sym_with_member_def_token1,
      aux_sym_with_member_def_token2,
      aux_sym_with_set_def_token1,
      anon_sym_DASH,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_select_statement_token1,
      aux_sym_axis_def_token3,
      aux_sym_dim_properties_token1,
      sym_identifier,
    ACTIONS(33), 18,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_LBRACE,
      anon_sym_COLON,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_AMP,
      sym_bracket_name,
      sym_number,
      sym_string_literal,
  [156] = 2,
    ACTIONS(21), 10,
      aux_sym_with_member_def_token1,
      aux_sym_with_member_def_token2,
      aux_sym_with_set_def_token1,
      anon_sym_DASH,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_select_statement_token1,
      aux_sym_axis_def_token3,
      aux_sym_dim_properties_token1,
      sym_identifier,
    ACTIONS(23), 18,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_LBRACE,
      anon_sym_COLON,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_AMP,
      sym_bracket_name,
      sym_number,
      sym_string_literal,
  [189] = 10,
    ACTIONS(35), 1,
      sym_identifier,
    ACTIONS(43), 1,
      anon_sym_LPAREN,
    ACTIONS(46), 1,
      anon_sym_RPAREN,
    ACTIONS(51), 1,
      sym_bracket_name,
    ACTIONS(54), 2,
      sym_number,
      sym_string_literal,
    STATE(7), 2,
      sym_calc_atom,
      aux_sym_calc_expression_repeat1,
    ACTIONS(41), 3,
      aux_sym_with_member_def_token1,
      aux_sym_with_set_def_token1,
      aux_sym_select_statement_token1,
    ACTIONS(48), 3,
      anon_sym_DASH,
      anon_sym_LT,
      anon_sym_GT,
    STATE(16), 3,
      sym_calc_paren,
      sym_operator,
      sym_dotted_ref,
    ACTIONS(38), 8,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [235] = 10,
    ACTIONS(57), 1,
      sym_identifier,
    ACTIONS(59), 1,
      anon_sym_COMMA,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(69), 1,
      sym_bracket_name,
    ACTIONS(71), 2,
      sym_number,
      sym_string_literal,
    STATE(7), 2,
      sym_calc_atom,
      aux_sym_calc_expression_repeat1,
    ACTIONS(61), 3,
      aux_sym_with_member_def_token1,
      aux_sym_with_set_def_token1,
      aux_sym_select_statement_token1,
    ACTIONS(67), 3,
      anon_sym_DASH,
      anon_sym_LT,
      anon_sym_GT,
    STATE(16), 3,
      sym_calc_paren,
      sym_operator,
      sym_dotted_ref,
    ACTIONS(63), 7,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [280] = 9,
    ACTIONS(57), 1,
      sym_identifier,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(69), 1,
      sym_bracket_name,
    ACTIONS(71), 2,
      sym_number,
      sym_string_literal,
    STATE(7), 2,
      sym_calc_atom,
      aux_sym_calc_expression_repeat1,
    ACTIONS(61), 3,
      aux_sym_with_member_def_token1,
      aux_sym_with_set_def_token1,
      aux_sym_select_statement_token1,
    ACTIONS(67), 3,
      anon_sym_DASH,
      anon_sym_LT,
      anon_sym_GT,
    STATE(16), 3,
      sym_calc_paren,
      sym_operator,
      sym_dotted_ref,
    ACTIONS(63), 8,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [323] = 8,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(69), 1,
      sym_bracket_name,
    STATE(84), 1,
      sym_calc_expression,
    STATE(9), 2,
      sym_calc_atom,
      aux_sym_calc_expression_repeat1,
    ACTIONS(67), 3,
      anon_sym_DASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(71), 3,
      sym_identifier,
      sym_number,
      sym_string_literal,
    STATE(16), 3,
      sym_calc_paren,
      sym_operator,
      sym_dotted_ref,
    ACTIONS(63), 8,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [362] = 8,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(69), 1,
      sym_bracket_name,
    STATE(48), 1,
      sym_calc_expression,
    STATE(8), 2,
      sym_calc_atom,
      aux_sym_calc_expression_repeat1,
    ACTIONS(67), 3,
      anon_sym_DASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(71), 3,
      sym_identifier,
      sym_number,
      sym_string_literal,
    STATE(16), 3,
      sym_calc_paren,
      sym_operator,
      sym_dotted_ref,
    ACTIONS(63), 8,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [401] = 8,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(69), 1,
      sym_bracket_name,
    ACTIONS(73), 1,
      anon_sym_RPAREN,
    STATE(13), 2,
      sym_calc_atom,
      aux_sym_calc_expression_repeat1,
    ACTIONS(67), 3,
      anon_sym_DASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(71), 3,
      sym_identifier,
      sym_number,
      sym_string_literal,
    STATE(16), 3,
      sym_calc_paren,
      sym_operator,
      sym_dotted_ref,
    ACTIONS(63), 8,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [440] = 8,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(69), 1,
      sym_bracket_name,
    ACTIONS(75), 1,
      anon_sym_RPAREN,
    STATE(7), 2,
      sym_calc_atom,
      aux_sym_calc_expression_repeat1,
    ACTIONS(67), 3,
      anon_sym_DASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(71), 3,
      sym_identifier,
      sym_number,
      sym_string_literal,
    STATE(16), 3,
      sym_calc_paren,
      sym_operator,
      sym_dotted_ref,
    ACTIONS(63), 8,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [479] = 2,
    ACTIONS(77), 7,
      aux_sym_with_member_def_token1,
      aux_sym_with_set_def_token1,
      anon_sym_DASH,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_select_statement_token1,
      sym_identifier,
    ACTIONS(79), 13,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_bracket_name,
      sym_number,
      sym_string_literal,
  [504] = 2,
    ACTIONS(81), 7,
      aux_sym_with_member_def_token1,
      aux_sym_with_set_def_token1,
      anon_sym_DASH,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_select_statement_token1,
      sym_identifier,
    ACTIONS(83), 13,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_bracket_name,
      sym_number,
      sym_string_literal,
  [529] = 2,
    ACTIONS(85), 7,
      aux_sym_with_member_def_token1,
      aux_sym_with_set_def_token1,
      anon_sym_DASH,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_select_statement_token1,
      sym_identifier,
    ACTIONS(87), 13,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_bracket_name,
      sym_number,
      sym_string_literal,
  [554] = 2,
    ACTIONS(89), 7,
      aux_sym_with_member_def_token1,
      aux_sym_with_set_def_token1,
      anon_sym_DASH,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_select_statement_token1,
      sym_identifier,
    ACTIONS(91), 13,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_bracket_name,
      sym_number,
      sym_string_literal,
  [579] = 11,
    ACTIONS(69), 1,
      sym_bracket_name,
    ACTIONS(93), 1,
      sym_identifier,
    ACTIONS(95), 1,
      aux_sym_select_statement_token2,
    ACTIONS(97), 1,
      aux_sym_axis_def_token1,
    ACTIONS(99), 1,
      anon_sym_LBRACE,
    STATE(69), 1,
      sym_axis_body,
    STATE(83), 1,
      sym_axis_def,
    STATE(111), 1,
      sym_axis_list,
    ACTIONS(101), 2,
      sym_number,
      sym_string_literal,
    STATE(26), 2,
      sym_axis_token,
      aux_sym_axis_body_repeat1,
    STATE(33), 3,
      sym_func_call,
      sym_set_literal,
      sym_dotted_ref,
  [617] = 9,
    ACTIONS(69), 1,
      sym_bracket_name,
    ACTIONS(93), 1,
      sym_identifier,
    ACTIONS(97), 1,
      aux_sym_axis_def_token1,
    ACTIONS(99), 1,
      anon_sym_LBRACE,
    STATE(69), 1,
      sym_axis_body,
    STATE(90), 1,
      sym_axis_def,
    ACTIONS(101), 2,
      sym_number,
      sym_string_literal,
    STATE(26), 2,
      sym_axis_token,
      aux_sym_axis_body_repeat1,
    STATE(33), 3,
      sym_func_call,
      sym_set_literal,
      sym_dotted_ref,
  [649] = 8,
    ACTIONS(69), 1,
      sym_bracket_name,
    ACTIONS(99), 1,
      anon_sym_LBRACE,
    ACTIONS(103), 1,
      sym_identifier,
    ACTIONS(107), 1,
      anon_sym_RBRACE,
    ACTIONS(101), 2,
      sym_number,
      sym_string_literal,
    ACTIONS(105), 2,
      anon_sym_COMMA,
      anon_sym_COLON,
    STATE(22), 2,
      sym_axis_token,
      aux_sym_set_literal_repeat1,
    STATE(33), 3,
      sym_func_call,
      sym_set_literal,
      sym_dotted_ref,
  [679] = 8,
    ACTIONS(69), 1,
      sym_bracket_name,
    ACTIONS(99), 1,
      anon_sym_LBRACE,
    ACTIONS(103), 1,
      sym_identifier,
    ACTIONS(111), 1,
      anon_sym_RBRACE,
    ACTIONS(101), 2,
      sym_number,
      sym_string_literal,
    ACTIONS(109), 2,
      anon_sym_COMMA,
      anon_sym_COLON,
    STATE(20), 2,
      sym_axis_token,
      aux_sym_set_literal_repeat1,
    STATE(33), 3,
      sym_func_call,
      sym_set_literal,
      sym_dotted_ref,
  [709] = 8,
    ACTIONS(113), 1,
      sym_identifier,
    ACTIONS(119), 1,
      anon_sym_LBRACE,
    ACTIONS(122), 1,
      anon_sym_RBRACE,
    ACTIONS(124), 1,
      sym_bracket_name,
    ACTIONS(116), 2,
      anon_sym_COMMA,
      anon_sym_COLON,
    ACTIONS(127), 2,
      sym_number,
      sym_string_literal,
    STATE(22), 2,
      sym_axis_token,
      aux_sym_set_literal_repeat1,
    STATE(33), 3,
      sym_func_call,
      sym_set_literal,
      sym_dotted_ref,
  [739] = 3,
    ACTIONS(134), 1,
      anon_sym_LPAREN,
    ACTIONS(130), 3,
      aux_sym_axis_def_token3,
      aux_sym_dim_properties_token1,
      sym_identifier,
    ACTIONS(132), 8,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COLON,
      anon_sym_RBRACE,
      sym_bracket_name,
      sym_number,
      sym_string_literal,
  [758] = 7,
    ACTIONS(136), 1,
      sym_identifier,
    ACTIONS(141), 1,
      anon_sym_LBRACE,
    ACTIONS(144), 1,
      sym_bracket_name,
    ACTIONS(139), 2,
      aux_sym_axis_def_token3,
      aux_sym_dim_properties_token1,
    ACTIONS(147), 2,
      sym_number,
      sym_string_literal,
    STATE(24), 2,
      sym_axis_token,
      aux_sym_axis_body_repeat1,
    STATE(33), 3,
      sym_func_call,
      sym_set_literal,
      sym_dotted_ref,
  [785] = 8,
    ACTIONS(69), 1,
      sym_bracket_name,
    ACTIONS(99), 1,
      anon_sym_LBRACE,
    ACTIONS(103), 1,
      sym_identifier,
    ACTIONS(150), 1,
      anon_sym_COMMA,
    ACTIONS(152), 1,
      anon_sym_RPAREN,
    ACTIONS(101), 2,
      sym_number,
      sym_string_literal,
    STATE(28), 2,
      sym_axis_token,
      aux_sym_func_call_repeat1,
    STATE(33), 3,
      sym_func_call,
      sym_set_literal,
      sym_dotted_ref,
  [814] = 7,
    ACTIONS(69), 1,
      sym_bracket_name,
    ACTIONS(93), 1,
      sym_identifier,
    ACTIONS(99), 1,
      anon_sym_LBRACE,
    ACTIONS(101), 2,
      sym_number,
      sym_string_literal,
    ACTIONS(154), 2,
      aux_sym_axis_def_token3,
      aux_sym_dim_properties_token1,
    STATE(24), 2,
      sym_axis_token,
      aux_sym_axis_body_repeat1,
    STATE(33), 3,
      sym_func_call,
      sym_set_literal,
      sym_dotted_ref,
  [841] = 8,
    ACTIONS(156), 1,
      sym_identifier,
    ACTIONS(159), 1,
      anon_sym_COMMA,
    ACTIONS(162), 1,
      anon_sym_RPAREN,
    ACTIONS(164), 1,
      anon_sym_LBRACE,
    ACTIONS(167), 1,
      sym_bracket_name,
    ACTIONS(170), 2,
      sym_number,
      sym_string_literal,
    STATE(27), 2,
      sym_axis_token,
      aux_sym_func_call_repeat1,
    STATE(33), 3,
      sym_func_call,
      sym_set_literal,
      sym_dotted_ref,
  [870] = 8,
    ACTIONS(69), 1,
      sym_bracket_name,
    ACTIONS(99), 1,
      anon_sym_LBRACE,
    ACTIONS(103), 1,
      sym_identifier,
    ACTIONS(173), 1,
      anon_sym_COMMA,
    ACTIONS(175), 1,
      anon_sym_RPAREN,
    ACTIONS(101), 2,
      sym_number,
      sym_string_literal,
    STATE(27), 2,
      sym_axis_token,
      aux_sym_func_call_repeat1,
    STATE(33), 3,
      sym_func_call,
      sym_set_literal,
      sym_dotted_ref,
  [899] = 2,
    ACTIONS(177), 3,
      aux_sym_axis_def_token3,
      aux_sym_dim_properties_token1,
      sym_identifier,
    ACTIONS(179), 8,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COLON,
      anon_sym_RBRACE,
      sym_bracket_name,
      sym_number,
      sym_string_literal,
  [915] = 7,
    ACTIONS(69), 1,
      sym_bracket_name,
    ACTIONS(99), 1,
      anon_sym_LBRACE,
    ACTIONS(103), 1,
      sym_identifier,
    STATE(74), 1,
      sym_axis_body,
    ACTIONS(101), 2,
      sym_number,
      sym_string_literal,
    STATE(26), 2,
      sym_axis_token,
      aux_sym_axis_body_repeat1,
    STATE(33), 3,
      sym_func_call,
      sym_set_literal,
      sym_dotted_ref,
  [941] = 2,
    ACTIONS(181), 3,
      aux_sym_axis_def_token3,
      aux_sym_dim_properties_token1,
      sym_identifier,
    ACTIONS(183), 8,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COLON,
      anon_sym_RBRACE,
      sym_bracket_name,
      sym_number,
      sym_string_literal,
  [957] = 2,
    ACTIONS(185), 3,
      aux_sym_axis_def_token3,
      aux_sym_dim_properties_token1,
      sym_identifier,
    ACTIONS(187), 8,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COLON,
      anon_sym_RBRACE,
      sym_bracket_name,
      sym_number,
      sym_string_literal,
  [973] = 2,
    ACTIONS(130), 3,
      aux_sym_axis_def_token3,
      aux_sym_dim_properties_token1,
      sym_identifier,
    ACTIONS(132), 8,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COLON,
      anon_sym_RBRACE,
      sym_bracket_name,
      sym_number,
      sym_string_literal,
  [989] = 2,
    ACTIONS(189), 3,
      aux_sym_axis_def_token3,
      aux_sym_dim_properties_token1,
      sym_identifier,
    ACTIONS(191), 8,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COLON,
      anon_sym_RBRACE,
      sym_bracket_name,
      sym_number,
      sym_string_literal,
  [1005] = 5,
    ACTIONS(69), 1,
      sym_bracket_name,
    ACTIONS(99), 1,
      anon_sym_LBRACE,
    ACTIONS(193), 1,
      anon_sym_COMMA,
    ACTIONS(195), 1,
      anon_sym_RPAREN,
    STATE(36), 3,
      sym_set_literal,
      sym_dotted_ref,
      aux_sym_where_tuple_repeat1,
  [1023] = 5,
    ACTIONS(197), 1,
      anon_sym_COMMA,
    ACTIONS(200), 1,
      anon_sym_RPAREN,
    ACTIONS(202), 1,
      anon_sym_LBRACE,
    ACTIONS(205), 1,
      sym_bracket_name,
    STATE(36), 3,
      sym_set_literal,
      sym_dotted_ref,
      aux_sym_where_tuple_repeat1,
  [1041] = 4,
    ACTIONS(208), 1,
      anon_sym_DOT,
    ACTIONS(211), 1,
      anon_sym_AMP,
    ACTIONS(23), 2,
      ts_builtin_sym_end,
      anon_sym_COMMA,
    STATE(37), 2,
      sym_ampersand_key,
      aux_sym_dotted_ref_repeat1,
  [1056] = 4,
    ACTIONS(214), 1,
      aux_sym_with_member_def_token1,
    ACTIONS(217), 1,
      aux_sym_with_set_def_token1,
    ACTIONS(220), 1,
      aux_sym_select_statement_token1,
    STATE(38), 3,
      sym_with_member_def,
      sym_with_set_def,
      aux_sym_with_clause_repeat1,
  [1071] = 4,
    ACTIONS(222), 1,
      aux_sym_with_member_def_token1,
    ACTIONS(224), 1,
      aux_sym_with_set_def_token1,
    ACTIONS(226), 1,
      aux_sym_select_statement_token1,
    STATE(38), 3,
      sym_with_member_def,
      sym_with_set_def,
      aux_sym_with_clause_repeat1,
  [1086] = 6,
    ACTIONS(5), 1,
      aux_sym_with_clause_token1,
    ACTIONS(7), 1,
      aux_sym_select_statement_token1,
    ACTIONS(228), 1,
      aux_sym_maxrows_clause_token1,
    STATE(59), 1,
      sym_maxrows_clause,
    STATE(81), 1,
      sym_select_statement,
    STATE(105), 1,
      sym_with_clause,
  [1105] = 4,
    ACTIONS(230), 1,
      anon_sym_DOT,
    ACTIONS(232), 1,
      anon_sym_AMP,
    ACTIONS(11), 2,
      ts_builtin_sym_end,
      anon_sym_COMMA,
    STATE(43), 2,
      sym_ampersand_key,
      aux_sym_dotted_ref_repeat1,
  [1120] = 4,
    ACTIONS(69), 1,
      sym_bracket_name,
    ACTIONS(99), 1,
      anon_sym_LBRACE,
    ACTIONS(234), 1,
      anon_sym_COMMA,
    STATE(35), 3,
      sym_set_literal,
      sym_dotted_ref,
      aux_sym_where_tuple_repeat1,
  [1135] = 4,
    ACTIONS(230), 1,
      anon_sym_DOT,
    ACTIONS(232), 1,
      anon_sym_AMP,
    ACTIONS(19), 2,
      ts_builtin_sym_end,
      anon_sym_COMMA,
    STATE(37), 2,
      sym_ampersand_key,
      aux_sym_dotted_ref_repeat1,
  [1150] = 3,
    ACTIONS(238), 1,
      aux_sym_where_clause_token1,
    STATE(85), 1,
      sym_where_clause,
    ACTIONS(236), 3,
      ts_builtin_sym_end,
      aux_sym_return_clause_token1,
      anon_sym_RPAREN,
  [1162] = 3,
    ACTIONS(222), 1,
      aux_sym_with_member_def_token1,
    ACTIONS(224), 1,
      aux_sym_with_set_def_token1,
    STATE(39), 3,
      sym_with_member_def,
      sym_with_set_def,
      aux_sym_with_clause_repeat1,
  [1174] = 3,
    ACTIONS(238), 1,
      aux_sym_where_clause_token1,
    STATE(70), 1,
      sym_where_clause,
    ACTIONS(240), 3,
      ts_builtin_sym_end,
      aux_sym_return_clause_token1,
      anon_sym_RPAREN,
  [1186] = 3,
    ACTIONS(242), 1,
      anon_sym_COMMA,
    STATE(47), 1,
      aux_sym_with_member_def_repeat1,
    ACTIONS(245), 3,
      aux_sym_with_member_def_token1,
      aux_sym_with_set_def_token1,
      aux_sym_select_statement_token1,
  [1198] = 3,
    ACTIONS(247), 1,
      anon_sym_COMMA,
    STATE(49), 1,
      aux_sym_with_member_def_repeat1,
    ACTIONS(249), 3,
      aux_sym_with_member_def_token1,
      aux_sym_with_set_def_token1,
      aux_sym_select_statement_token1,
  [1210] = 3,
    ACTIONS(247), 1,
      anon_sym_COMMA,
    STATE(47), 1,
      aux_sym_with_member_def_repeat1,
    ACTIONS(251), 3,
      aux_sym_with_member_def_token1,
      aux_sym_with_set_def_token1,
      aux_sym_select_statement_token1,
  [1222] = 1,
    ACTIONS(33), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_AMP,
  [1229] = 3,
    ACTIONS(232), 1,
      anon_sym_AMP,
    STATE(65), 1,
      sym_ampersand_key,
    ACTIONS(253), 2,
      sym_bracket_name,
      sym_identifier,
  [1240] = 1,
    ACTIONS(255), 4,
      ts_builtin_sym_end,
      aux_sym_return_clause_token1,
      anon_sym_RPAREN,
      aux_sym_where_clause_token1,
  [1247] = 4,
    ACTIONS(257), 1,
      anon_sym_LPAREN,
    ACTIONS(259), 1,
      sym_bracket_name,
    STATE(44), 1,
      sym_from_clause,
    STATE(52), 1,
      sym_subselect,
  [1260] = 2,
    STATE(93), 1,
      sym_axis_id,
    ACTIONS(261), 3,
      aux_sym_axis_id_token1,
      aux_sym_axis_id_token2,
      aux_sym_axis_id_token3,
  [1269] = 3,
    ACTIONS(15), 1,
      anon_sym_AMP,
    STATE(6), 1,
      sym_ampersand_key,
    ACTIONS(263), 2,
      sym_bracket_name,
      sym_identifier,
  [1280] = 1,
    ACTIONS(265), 4,
      ts_builtin_sym_end,
      aux_sym_return_clause_token1,
      anon_sym_RPAREN,
      aux_sym_where_clause_token1,
  [1287] = 2,
    STATE(99), 1,
      sym_axis_id,
    ACTIONS(261), 3,
      aux_sym_axis_id_token1,
      aux_sym_axis_id_token2,
      aux_sym_axis_id_token3,
  [1296] = 4,
    ACTIONS(257), 1,
      anon_sym_LPAREN,
    ACTIONS(259), 1,
      sym_bracket_name,
    STATE(46), 1,
      sym_from_clause,
    STATE(52), 1,
      sym_subselect,
  [1309] = 4,
    ACTIONS(5), 1,
      aux_sym_with_clause_token1,
    ACTIONS(7), 1,
      aux_sym_select_statement_token1,
    STATE(87), 1,
      sym_select_statement,
    STATE(102), 1,
      sym_with_clause,
  [1322] = 2,
    STATE(103), 1,
      sym_axis_id,
    ACTIONS(261), 3,
      aux_sym_axis_id_token1,
      aux_sym_axis_id_token2,
      aux_sym_axis_id_token3,
  [1331] = 1,
    ACTIONS(245), 4,
      anon_sym_COMMA,
      aux_sym_with_member_def_token1,
      aux_sym_with_set_def_token1,
      aux_sym_select_statement_token1,
  [1338] = 2,
    STATE(95), 1,
      sym_axis_id,
    ACTIONS(261), 3,
      aux_sym_axis_id_token1,
      aux_sym_axis_id_token2,
      aux_sym_axis_id_token3,
  [1347] = 3,
    ACTIONS(69), 1,
      sym_bracket_name,
    STATE(64), 1,
      sym_dotted_ref,
    ACTIONS(267), 2,
      sym_number,
      sym_string_literal,
  [1358] = 1,
    ACTIONS(269), 4,
      anon_sym_COMMA,
      aux_sym_with_member_def_token1,
      aux_sym_with_set_def_token1,
      aux_sym_select_statement_token1,
  [1365] = 1,
    ACTIONS(23), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_AMP,
  [1372] = 1,
    ACTIONS(271), 3,
      ts_builtin_sym_end,
      aux_sym_return_clause_token1,
      anon_sym_RPAREN,
  [1378] = 3,
    ACTIONS(273), 1,
      ts_builtin_sym_end,
    ACTIONS(275), 1,
      anon_sym_COMMA,
    STATE(78), 1,
      aux_sym_return_clause_repeat1,
  [1388] = 3,
    ACTIONS(277), 1,
      anon_sym_COMMA,
    ACTIONS(280), 1,
      aux_sym_select_statement_token2,
    STATE(68), 1,
      aux_sym_axis_list_repeat1,
  [1398] = 3,
    ACTIONS(282), 1,
      aux_sym_axis_def_token3,
    ACTIONS(284), 1,
      aux_sym_dim_properties_token1,
    STATE(119), 1,
      sym_dim_properties,
  [1408] = 1,
    ACTIONS(286), 3,
      ts_builtin_sym_end,
      aux_sym_return_clause_token1,
      anon_sym_RPAREN,
  [1414] = 3,
    ACTIONS(288), 1,
      anon_sym_COMMA,
    ACTIONS(290), 1,
      aux_sym_axis_def_token3,
    STATE(77), 1,
      aux_sym_dim_properties_repeat1,
  [1424] = 3,
    ACTIONS(292), 1,
      ts_builtin_sym_end,
    ACTIONS(294), 1,
      anon_sym_COMMA,
    STATE(72), 1,
      aux_sym_return_clause_repeat1,
  [1434] = 3,
    ACTIONS(69), 1,
      sym_bracket_name,
    ACTIONS(297), 1,
      sym_identifier,
    STATE(71), 1,
      sym_dotted_ref,
  [1444] = 3,
    ACTIONS(284), 1,
      aux_sym_dim_properties_token1,
    ACTIONS(299), 1,
      aux_sym_axis_def_token3,
    STATE(124), 1,
      sym_dim_properties,
  [1454] = 3,
    ACTIONS(301), 1,
      sym_bracket_name,
    STATE(94), 1,
      sym_return_column,
    STATE(97), 1,
      sym_dotted_ref,
  [1464] = 3,
    ACTIONS(69), 1,
      sym_bracket_name,
    ACTIONS(303), 1,
      sym_identifier,
    STATE(89), 1,
      sym_dotted_ref,
  [1474] = 3,
    ACTIONS(288), 1,
      anon_sym_COMMA,
    ACTIONS(305), 1,
      aux_sym_axis_def_token3,
    STATE(82), 1,
      aux_sym_dim_properties_repeat1,
  [1484] = 3,
    ACTIONS(275), 1,
      anon_sym_COMMA,
    ACTIONS(307), 1,
      ts_builtin_sym_end,
    STATE(72), 1,
      aux_sym_return_clause_repeat1,
  [1494] = 3,
    ACTIONS(309), 1,
      anon_sym_COMMA,
    ACTIONS(311), 1,
      aux_sym_select_statement_token2,
    STATE(68), 1,
      aux_sym_axis_list_repeat1,
  [1504] = 1,
    ACTIONS(313), 3,
      ts_builtin_sym_end,
      aux_sym_return_clause_token1,
      anon_sym_RPAREN,
  [1510] = 3,
    ACTIONS(315), 1,
      ts_builtin_sym_end,
    ACTIONS(317), 1,
      aux_sym_return_clause_token1,
    STATE(114), 1,
      sym_return_clause,
  [1520] = 3,
    ACTIONS(319), 1,
      anon_sym_COMMA,
    ACTIONS(322), 1,
      aux_sym_axis_def_token3,
    STATE(82), 1,
      aux_sym_dim_properties_repeat1,
  [1530] = 3,
    ACTIONS(309), 1,
      anon_sym_COMMA,
    ACTIONS(324), 1,
      aux_sym_select_statement_token2,
    STATE(79), 1,
      aux_sym_axis_list_repeat1,
  [1540] = 1,
    ACTIONS(326), 3,
      aux_sym_with_member_def_token1,
      aux_sym_with_set_def_token1,
      aux_sym_select_statement_token1,
  [1546] = 1,
    ACTIONS(240), 3,
      ts_builtin_sym_end,
      aux_sym_return_clause_token1,
      anon_sym_RPAREN,
  [1552] = 3,
    ACTIONS(301), 1,
      sym_bracket_name,
    STATE(67), 1,
      sym_return_column,
    STATE(97), 1,
      sym_dotted_ref,
  [1562] = 3,
    ACTIONS(317), 1,
      aux_sym_return_clause_token1,
    ACTIONS(328), 1,
      ts_builtin_sym_end,
    STATE(122), 1,
      sym_return_clause,
  [1572] = 3,
    ACTIONS(317), 1,
      aux_sym_return_clause_token1,
    ACTIONS(330), 1,
      ts_builtin_sym_end,
    STATE(113), 1,
      sym_return_clause,
  [1582] = 1,
    ACTIONS(322), 2,
      anon_sym_COMMA,
      aux_sym_axis_def_token3,
  [1587] = 1,
    ACTIONS(280), 2,
      anon_sym_COMMA,
      aux_sym_select_statement_token2,
  [1592] = 2,
    ACTIONS(332), 1,
      anon_sym_LPAREN,
    STATE(66), 1,
      sym_where_tuple,
  [1599] = 1,
    ACTIONS(334), 2,
      anon_sym_COMMA,
      aux_sym_select_statement_token2,
  [1604] = 1,
    ACTIONS(336), 2,
      anon_sym_COMMA,
      aux_sym_select_statement_token2,
  [1609] = 1,
    ACTIONS(292), 2,
      ts_builtin_sym_end,
      anon_sym_COMMA,
  [1614] = 1,
    ACTIONS(338), 2,
      anon_sym_COMMA,
      aux_sym_select_statement_token2,
  [1619] = 2,
    ACTIONS(340), 1,
      sym_identifier,
    STATE(61), 1,
      sym_member_property,
  [1626] = 1,
    ACTIONS(342), 2,
      ts_builtin_sym_end,
      anon_sym_COMMA,
  [1631] = 1,
    ACTIONS(344), 2,
      aux_sym_with_clause_token1,
      aux_sym_select_statement_token1,
  [1636] = 1,
    ACTIONS(346), 2,
      anon_sym_COMMA,
      aux_sym_select_statement_token2,
  [1641] = 2,
    ACTIONS(69), 1,
      sym_bracket_name,
    STATE(117), 1,
      sym_dotted_ref,
  [1648] = 2,
    ACTIONS(69), 1,
      sym_bracket_name,
    STATE(110), 1,
      sym_dotted_ref,
  [1655] = 2,
    ACTIONS(7), 1,
      aux_sym_select_statement_token1,
    STATE(88), 1,
      sym_select_statement,
  [1662] = 1,
    ACTIONS(348), 2,
      anon_sym_COMMA,
      aux_sym_select_statement_token2,
  [1667] = 2,
    ACTIONS(7), 1,
      aux_sym_select_statement_token1,
    STATE(115), 1,
      sym_select_statement,
  [1674] = 2,
    ACTIONS(7), 1,
      aux_sym_select_statement_token1,
    STATE(87), 1,
      sym_select_statement,
  [1681] = 2,
    ACTIONS(7), 1,
      aux_sym_select_statement_token1,
    STATE(123), 1,
      sym_select_statement,
  [1688] = 1,
    ACTIONS(350), 1,
      aux_sym_dim_properties_token2,
  [1692] = 1,
    ACTIONS(352), 1,
      anon_sym_EQ,
  [1696] = 1,
    ACTIONS(354), 1,
      ts_builtin_sym_end,
  [1700] = 1,
    ACTIONS(356), 1,
      aux_sym_with_member_def_token2,
  [1704] = 1,
    ACTIONS(358), 1,
      aux_sym_select_statement_token2,
  [1708] = 1,
    ACTIONS(360), 1,
      sym_bracket_name,
  [1712] = 1,
    ACTIONS(362), 1,
      ts_builtin_sym_end,
  [1716] = 1,
    ACTIONS(328), 1,
      ts_builtin_sym_end,
  [1720] = 1,
    ACTIONS(364), 1,
      anon_sym_RPAREN,
  [1724] = 1,
    ACTIONS(366), 1,
      aux_sym_axis_def_token2,
  [1728] = 1,
    ACTIONS(368), 1,
      aux_sym_with_member_def_token2,
  [1732] = 1,
    ACTIONS(370), 1,
      sym_number,
  [1736] = 1,
    ACTIONS(372), 1,
      aux_sym_axis_def_token3,
  [1740] = 1,
    ACTIONS(374), 1,
      ts_builtin_sym_end,
  [1744] = 1,
    ACTIONS(376), 1,
      ts_builtin_sym_end,
  [1748] = 1,
    ACTIONS(330), 1,
      ts_builtin_sym_end,
  [1752] = 1,
    ACTIONS(378), 1,
      ts_builtin_sym_end,
  [1756] = 1,
    ACTIONS(380), 1,
      aux_sym_axis_def_token3,
  [1760] = 1,
    ACTIONS(382), 1,
      sym_bracket_name,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 41,
  [SMALL_STATE(4)] = 82,
  [SMALL_STATE(5)] = 123,
  [SMALL_STATE(6)] = 156,
  [SMALL_STATE(7)] = 189,
  [SMALL_STATE(8)] = 235,
  [SMALL_STATE(9)] = 280,
  [SMALL_STATE(10)] = 323,
  [SMALL_STATE(11)] = 362,
  [SMALL_STATE(12)] = 401,
  [SMALL_STATE(13)] = 440,
  [SMALL_STATE(14)] = 479,
  [SMALL_STATE(15)] = 504,
  [SMALL_STATE(16)] = 529,
  [SMALL_STATE(17)] = 554,
  [SMALL_STATE(18)] = 579,
  [SMALL_STATE(19)] = 617,
  [SMALL_STATE(20)] = 649,
  [SMALL_STATE(21)] = 679,
  [SMALL_STATE(22)] = 709,
  [SMALL_STATE(23)] = 739,
  [SMALL_STATE(24)] = 758,
  [SMALL_STATE(25)] = 785,
  [SMALL_STATE(26)] = 814,
  [SMALL_STATE(27)] = 841,
  [SMALL_STATE(28)] = 870,
  [SMALL_STATE(29)] = 899,
  [SMALL_STATE(30)] = 915,
  [SMALL_STATE(31)] = 941,
  [SMALL_STATE(32)] = 957,
  [SMALL_STATE(33)] = 973,
  [SMALL_STATE(34)] = 989,
  [SMALL_STATE(35)] = 1005,
  [SMALL_STATE(36)] = 1023,
  [SMALL_STATE(37)] = 1041,
  [SMALL_STATE(38)] = 1056,
  [SMALL_STATE(39)] = 1071,
  [SMALL_STATE(40)] = 1086,
  [SMALL_STATE(41)] = 1105,
  [SMALL_STATE(42)] = 1120,
  [SMALL_STATE(43)] = 1135,
  [SMALL_STATE(44)] = 1150,
  [SMALL_STATE(45)] = 1162,
  [SMALL_STATE(46)] = 1174,
  [SMALL_STATE(47)] = 1186,
  [SMALL_STATE(48)] = 1198,
  [SMALL_STATE(49)] = 1210,
  [SMALL_STATE(50)] = 1222,
  [SMALL_STATE(51)] = 1229,
  [SMALL_STATE(52)] = 1240,
  [SMALL_STATE(53)] = 1247,
  [SMALL_STATE(54)] = 1260,
  [SMALL_STATE(55)] = 1269,
  [SMALL_STATE(56)] = 1280,
  [SMALL_STATE(57)] = 1287,
  [SMALL_STATE(58)] = 1296,
  [SMALL_STATE(59)] = 1309,
  [SMALL_STATE(60)] = 1322,
  [SMALL_STATE(61)] = 1331,
  [SMALL_STATE(62)] = 1338,
  [SMALL_STATE(63)] = 1347,
  [SMALL_STATE(64)] = 1358,
  [SMALL_STATE(65)] = 1365,
  [SMALL_STATE(66)] = 1372,
  [SMALL_STATE(67)] = 1378,
  [SMALL_STATE(68)] = 1388,
  [SMALL_STATE(69)] = 1398,
  [SMALL_STATE(70)] = 1408,
  [SMALL_STATE(71)] = 1414,
  [SMALL_STATE(72)] = 1424,
  [SMALL_STATE(73)] = 1434,
  [SMALL_STATE(74)] = 1444,
  [SMALL_STATE(75)] = 1454,
  [SMALL_STATE(76)] = 1464,
  [SMALL_STATE(77)] = 1474,
  [SMALL_STATE(78)] = 1484,
  [SMALL_STATE(79)] = 1494,
  [SMALL_STATE(80)] = 1504,
  [SMALL_STATE(81)] = 1510,
  [SMALL_STATE(82)] = 1520,
  [SMALL_STATE(83)] = 1530,
  [SMALL_STATE(84)] = 1540,
  [SMALL_STATE(85)] = 1546,
  [SMALL_STATE(86)] = 1552,
  [SMALL_STATE(87)] = 1562,
  [SMALL_STATE(88)] = 1572,
  [SMALL_STATE(89)] = 1582,
  [SMALL_STATE(90)] = 1587,
  [SMALL_STATE(91)] = 1592,
  [SMALL_STATE(92)] = 1599,
  [SMALL_STATE(93)] = 1604,
  [SMALL_STATE(94)] = 1609,
  [SMALL_STATE(95)] = 1614,
  [SMALL_STATE(96)] = 1619,
  [SMALL_STATE(97)] = 1626,
  [SMALL_STATE(98)] = 1631,
  [SMALL_STATE(99)] = 1636,
  [SMALL_STATE(100)] = 1641,
  [SMALL_STATE(101)] = 1648,
  [SMALL_STATE(102)] = 1655,
  [SMALL_STATE(103)] = 1662,
  [SMALL_STATE(104)] = 1667,
  [SMALL_STATE(105)] = 1674,
  [SMALL_STATE(106)] = 1681,
  [SMALL_STATE(107)] = 1688,
  [SMALL_STATE(108)] = 1692,
  [SMALL_STATE(109)] = 1696,
  [SMALL_STATE(110)] = 1700,
  [SMALL_STATE(111)] = 1704,
  [SMALL_STATE(112)] = 1708,
  [SMALL_STATE(113)] = 1712,
  [SMALL_STATE(114)] = 1716,
  [SMALL_STATE(115)] = 1720,
  [SMALL_STATE(116)] = 1724,
  [SMALL_STATE(117)] = 1728,
  [SMALL_STATE(118)] = 1732,
  [SMALL_STATE(119)] = 1736,
  [SMALL_STATE(120)] = 1740,
  [SMALL_STATE(121)] = 1744,
  [SMALL_STATE(122)] = 1748,
  [SMALL_STATE(123)] = 1752,
  [SMALL_STATE(124)] = 1756,
  [SMALL_STATE(125)] = 1760,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [9] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dotted_ref, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dotted_ref, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dotted_ref, 2, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dotted_ref, 2, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_dotted_ref_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dotted_ref_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dotted_ref_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dotted_ref_repeat1, 2, 0, 0), SHIFT_REPEAT(112),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ampersand_key, 2, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ampersand_key, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_calc_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_calc_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_calc_expression_repeat1, 2, 0, 0),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_calc_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_calc_expression_repeat1, 2, 0, 0),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_calc_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_calc_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_calc_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_calc_expression, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_calc_expression, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operator, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_calc_paren, 2, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_calc_paren, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_calc_atom, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_calc_atom, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_calc_paren, 3, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_calc_paren, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(116),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [113] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_set_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [116] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_set_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [119] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_set_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_set_literal_repeat1, 2, 0, 0),
  [124] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_set_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [127] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_set_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_axis_token, 1, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_axis_token, 1, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [136] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_axis_body_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_axis_body_repeat1, 2, 0, 0),
  [141] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_axis_body_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [144] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_axis_body_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [147] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_axis_body_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_axis_body, 1, 0, 0),
  [156] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_func_call_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [159] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_func_call_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_func_call_repeat1, 2, 0, 0),
  [164] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_func_call_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [167] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_func_call_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [170] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_func_call_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_func_call, 3, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_call, 3, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set_literal, 2, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set_literal, 2, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set_literal, 3, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set_literal, 3, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_func_call, 4, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_call, 4, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [197] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_where_tuple_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_where_tuple_repeat1, 2, 0, 0),
  [202] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_where_tuple_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [205] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_where_tuple_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [208] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dotted_ref_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [211] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dotted_ref_repeat1, 2, 0, 0), SHIFT_REPEAT(125),
  [214] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_with_clause_repeat1, 2, 0, 0), SHIFT_REPEAT(100),
  [217] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_with_clause_repeat1, 2, 0, 0), SHIFT_REPEAT(101),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_with_clause_repeat1, 2, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_with_clause, 2, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_select_statement, 3, 0, 0),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_select_statement, 4, 0, 0),
  [242] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_with_member_def_repeat1, 2, 0, 0), SHIFT_REPEAT(96),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_with_member_def_repeat1, 2, 0, 0),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_with_member_def, 4, 0, 3),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_with_member_def, 5, 0, 3),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_from_clause, 1, 0, 0),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subselect, 3, 0, 0),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_member_property, 3, 0, 0),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_where_clause, 2, 0, 0),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_clause, 2, 0, 0),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [277] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_axis_list_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_axis_list_repeat1, 2, 0, 0),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_select_statement, 5, 0, 0),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dim_properties, 3, 0, 0),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_return_clause_repeat1, 2, 0, 0),
  [294] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_return_clause_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [305] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dim_properties, 4, 0, 0),
  [307] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_clause, 3, 0, 0),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [311] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_axis_list, 2, 0, 0),
  [313] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_where_tuple, 3, 0, 0),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_drillthrough_statement, 2, 0, 0),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [319] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dim_properties_repeat1, 2, 0, 0), SHIFT_REPEAT(76),
  [322] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dim_properties_repeat1, 2, 0, 0),
  [324] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_axis_list, 1, 0, 0),
  [326] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_with_set_def, 4, 0, 3),
  [328] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_drillthrough_statement, 3, 0, 0),
  [330] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_drillthrough_statement, 4, 0, 0),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [334] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_axis_id, 1, 0, 0),
  [336] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_axis_def, 4, 0, 4),
  [338] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_axis_def, 3, 0, 2),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [342] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_column, 1, 0, 0),
  [344] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_maxrows_clause, 2, 0, 1),
  [346] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_axis_def, 5, 0, 5),
  [348] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_axis_def, 6, 0, 6),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [354] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [362] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_drillthrough_statement, 5, 0, 0),
  [364] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [366] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [368] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [370] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [372] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [374] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mdx_statement, 1, 0, 0),
  [376] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [378] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mdx_statement, 2, 0, 0),
  [380] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [382] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_mdx(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
