"""Phase RA-1 — dimension aliases. Unbind calendars from sources, attach
calendar role to model_tables instead, and let each time-variant measure
pick its own calendar.

Schema changes:
- ADD ``model_tables.calendar_table_id`` (NULL, FK -> calendar_tables.id,
  ON DELETE SET NULL). When set, this ModelTable row is a calendar alias;
  the time-variant resolver consults the linked CalendarTable for the
  date / year / quarter / month / week / day column meanings.
- ADD ``measures.calendar_model_table_id`` (NULL, FK -> model_tables.id,
  ON DELETE SET NULL). Required at the API layer when the measure has any
  time-variant enabled; replaces the implicit "the source's calendar"
  lookup that used ``data_sources.calendar_table_id``.
- DROP ``data_sources.calendar_table_id``. After this migration, calendars
  are not bound at the source level — they are normal aliased dimensions.

Booster (per Q6 of the open-questions doc):
- Delete every measure with ``variant_kind IS NOT NULL`` so existing
  auto-generated time variants are wiped. Users recreate them through
  the new alias-aware measure dialog. CalendarTable rows themselves are
  preserved; they become unbound dimensions that the user can re-attach
  via the new alias flow.

Revision ID: 0048
Revises: 0047
Create Date: 2026-04-26
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


revision = "0048"
down_revision = "0047"
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    table_names = set(inspector.get_table_names())

    # Tenant-only tables; system schema runs this migration as a no-op.
    if "model_tables" not in table_names:
        return

    # 1. ADD model_tables.calendar_table_id
    mt_cols = {c["name"] for c in inspector.get_columns("model_tables")}
    if "calendar_table_id" not in mt_cols:
        op.add_column(
            "model_tables",
            sa.Column(
                "calendar_table_id",
                postgresql.UUID(as_uuid=True),
                sa.ForeignKey("calendar_tables.id", ondelete="SET NULL"),
                nullable=True,
            ),
        )
        op.create_index(
            "ix_model_tables_calendar_table_id",
            "model_tables",
            ["calendar_table_id"],
        )

    # 2. ADD measures.calendar_model_table_id
    if "measures" in table_names:
        m_cols = {c["name"] for c in inspector.get_columns("measures")}
        if "calendar_model_table_id" not in m_cols:
            op.add_column(
                "measures",
                sa.Column(
                    "calendar_model_table_id",
                    postgresql.UUID(as_uuid=True),
                    sa.ForeignKey("model_tables.id", ondelete="SET NULL"),
                    nullable=True,
                ),
            )
            op.create_index(
                "ix_measures_calendar_model_table_id",
                "measures",
                ["calendar_model_table_id"],
            )

    # 3. Booster — drop every auto-generated time-variant measure. Base
    # measures (variant_kind IS NULL) are preserved. CASCADE on
    # variant_of_measure_id is not needed here because the rows being
    # deleted are the variant rows themselves.
    if "measures" in table_names:
        op.execute(
            sa.text("DELETE FROM measures WHERE variant_kind IS NOT NULL")
        )

    # 4. DROP data_sources.calendar_table_id (and its index/FK if any).
    if "data_sources" in table_names:
        ds_cols = {c["name"] for c in inspector.get_columns("data_sources")}
        if "calendar_table_id" in ds_cols:
            # Drop FK constraint by name search (constraint name is
            # autogenerated by SQLAlchemy; look it up from the catalog).
            for fk in inspector.get_foreign_keys("data_sources"):
                if fk.get("constrained_columns") == ["calendar_table_id"]:
                    op.drop_constraint(
                        fk["name"], "data_sources", type_="foreignkey"
                    )
                    break
            op.drop_column("data_sources", "calendar_table_id")


def downgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    table_names = set(inspector.get_table_names())

    if "model_tables" not in table_names:
        return

    if "data_sources" in table_names:
        ds_cols = {c["name"] for c in inspector.get_columns("data_sources")}
        if "calendar_table_id" not in ds_cols:
            op.add_column(
                "data_sources",
                sa.Column(
                    "calendar_table_id",
                    postgresql.UUID(as_uuid=True),
                    sa.ForeignKey("calendar_tables.id", ondelete="SET NULL"),
                    nullable=True,
                ),
            )

    if "measures" in table_names:
        m_cols = {c["name"] for c in inspector.get_columns("measures")}
        if "calendar_model_table_id" in m_cols:
            try:
                op.drop_index(
                    "ix_measures_calendar_model_table_id",
                    table_name="measures",
                )
            except Exception:
                pass
            op.drop_column("measures", "calendar_model_table_id")

    mt_cols = {c["name"] for c in inspector.get_columns("model_tables")}
    if "calendar_table_id" in mt_cols:
        try:
            op.drop_index(
                "ix_model_tables_calendar_table_id",
                table_name="model_tables",
            )
        except Exception:
            pass
        op.drop_column("model_tables", "calendar_table_id")
