"""Project Agent Configuration CRUD.

Endpoints:
  GET    /projects/{project_id}/agent/config        — fetch (or empty 404)
  PUT    /projects/{project_id}/agent/config        — upsert config
  GET    /projects/{project_id}/agent/models        — list allow-list models
  PUT    /projects/{project_id}/agent/models        — replace allow-list (idempotent)
  GET    /projects/{project_id}/agent/model-context/{model_id}
  PUT    /projects/{project_id}/agent/model-context/{model_id}

Phase Agent-A1 surface only — judge / recipes / webhook tabs land in B & C.

Tenant-scoped DB; project bindings checked via UserAccessBinding (admin or
modeller). Enabling the agent requires an LLM config (answer_llm_config_id)
and at least one model in the allow-list. All other fields are optional.
"""
from __future__ import annotations

import logging
from typing import Optional
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, ConfigDict, Field
from sqlalchemy import select

from shared.config.settings import get_settings
from shared.db.models import (
    AgentJudgeRubric,
    Model,
    Project,
    ProjectAgentConfig,
    ProjectAgentModel,
    ProjectAgentModelContext,
    UserAccessBinding,
)
from shared.db.session import get_tenant_db


# ---------------------------------------------------------------------------
# Template defaults — applied once when agent config is first created
# ---------------------------------------------------------------------------

_TEMPLATE_DEFAULTS: dict[str, object] = {
    "display_name": "Analytics Assistant",
    "project_brief": (
        "Describe your project here: what data sources it covers, "
        "which semantic models are available, and what kinds of "
        "questions users typically ask."
    ),
    "agent_role": "data analyst",
    "tone_overrides": (
        "Be concise. Lead with the number or insight, then explain. "
        "Use business terminology rather than technical jargon."
    ),
    "brand_guidelines": (
        "Refer to the organisation by its proper name. "
        "Currency amounts should include the currency code "
        "(e.g. USD 1,234.56)."
    ),
    "safety_policy": (
        "Never reveal raw database credentials, connection strings, "
        "or internal schema names. Do not generate queries that bypass "
        "row-security filters. Decline requests for personally "
        "identifiable information (PII) and explain why."
    ),
    "content_rules": (
        "Include the time range of the data when answering trend or "
        "comparison questions. Show absolute numbers alongside "
        "percentages. Round currency to 2 decimal places and counts "
        "to whole numbers."
    ),
    "disclosure_text": (
        "This response was generated by an AI assistant using the "
        "project's semantic layer. Results are based on the data "
        "available at query time and should be verified for critical "
        "decisions."
    ),
    "enable_agent_log_screen": True,
    "conversation_retention_days": 90,
    "chart_renderer": "echarts",
}

_DEFAULT_RUBRIC_SECTIONS: list[dict] = [
    {
        "title": "Factual accuracy",
        "body": "The answer must be consistent with the data returned by the query.",
        "bullets": [
            "Numbers in the answer match the result set exactly",
            "No invented or hallucinated data points",
            "Correct currency and unit labels",
        ],
    },
    {
        "title": "Query correctness",
        "body": "The generated SQL or semantic query must be valid and answer the question asked.",
        "bullets": [
            "Correct measures and dimensions selected for the question",
            "Appropriate filters and date ranges applied",
            "Aggregation level matches the question granularity",
        ],
    },
    {
        "title": "Completeness",
        "body": "The answer should fully address the question without requiring follow-up.",
        "bullets": [
            "All parts of a multi-part question are answered",
            "Time range and scope are stated",
            "Ambiguity in the question is acknowledged if present",
        ],
    },
    {
        "title": "Presentation",
        "body": "The answer should be clear, well-structured, and follow brand guidelines.",
        "bullets": [
            "Currency amounts include currency code",
            "Percentages accompanied by absolute numbers",
            "No raw SQL or schema names exposed to the user",
        ],
    },
]
from src.auth.middleware import (
    CurrentEmbedUser,
    CurrentUser,
    forbid_embed_user,
    require_capability,
)
from src.derived.context import (
    derive_all_for_project,
    derive_model_context,
)

logger = logging.getLogger(__name__)
settings = get_settings()
router = APIRouter(prefix="/projects/{project_id}/agent", tags=["agent-config"])


# ---------------------------------------------------------------------------
# RBAC helpers — mirror the model-service pattern
# ---------------------------------------------------------------------------

# Bug-1082 — role vocabulary unification. The platform stores exactly one
# spelling, "modeler" (model-service rbac.py ROLE_HIERARCHY, the SPA
# AccessRole type, migration 0014 user_access_bindings; verified live: no
# tenant schema holds a "modeller" binding). Bug-1079/1070 added an interim
# accept-both ("modeller") because the agent-service gates matched the
# legacy spelling only; that interim is now removed and every agent-service
# gate matches the canonical "modeler" alone. "admin" remains a valid
# project-binding role (distinct from the JWT-level tenant_admin).
_MODELER_BINDING_ROLES = ("admin", "modeler")


async def _require_project_modeller(
    project_id: UUID, current_user: CurrentUser
) -> None:
    """Modeller or admin role on the project, or bootstrap path."""
    if current_user.role == "tenant_admin":
        return
    async for db in get_tenant_db(current_user.tenant_id):
        result = await db.execute(
            select(UserAccessBinding).where(
                UserAccessBinding.user_identity == current_user.user_id,
                UserAccessBinding.role.in_(_MODELER_BINDING_ROLES),
                (UserAccessBinding.project_id == project_id)
                | (UserAccessBinding.project_id.is_(None)),
            ).limit(1)
        )
        if result.scalar_one_or_none() is not None:
            return
        any_binding = await db.execute(select(UserAccessBinding).limit(1))
        if any_binding.scalar_one_or_none() is None:
            return
    raise HTTPException(
        status_code=status.HTTP_403_FORBIDDEN,
        detail="Modeller or Admin access required",
    )


async def _require_blocked_original_access(
    project_id: UUID, current_user: CurrentUser
) -> None:
    """F-023-01 (round 2) — strict gate for surfaces that can disclose
    judge-blocked original answers (``/agent/calibration``, ``/agent/log``).

    Unlike ``_require_project_modeller`` this NEVER bootstrap-opens: a
    tenant with zero ``UserAccessBinding`` rows fails CLOSED. The
    bootstrap-open posture (accepted-risk decision D2) covers
    configuration endpoints during first-run setup only — it must not
    gate content disclosure, because a binding-less tenant would expose
    blocked originals to every authenticated user. Access requires a
    privileged role on the JWT (tenant_admin / system_admin) or an
    explicit admin/modeller binding on the project (or tenant-wide).
    """
    if current_user.role in ("tenant_admin", "system_admin"):
        return
    async for db in get_tenant_db(current_user.tenant_id):
        result = await db.execute(
            select(UserAccessBinding).where(
                UserAccessBinding.user_identity == current_user.user_id,
                UserAccessBinding.role.in_(_MODELER_BINDING_ROLES),
                (UserAccessBinding.project_id == project_id)
                | (UserAccessBinding.project_id.is_(None)),
            ).limit(1)
        )
        if result.scalar_one_or_none() is not None:
            return
    raise HTTPException(
        status_code=status.HTTP_403_FORBIDDEN,
        detail=(
            "Tenant admin role or an explicit project Modeller/Admin "
            "binding is required to view judge trace data"
        ),
    )


async def _require_project_viewer(
    project_id: UUID, current_user: CurrentUser
) -> None:
    # Tenant admins have implicit read access to all project agent endpoints.
    if current_user.role == "tenant_admin":
        return
    async for db in get_tenant_db(current_user.tenant_id):
        result = await db.execute(
            select(UserAccessBinding).where(
                UserAccessBinding.user_identity == current_user.user_id,
            ).limit(1)
        )
        if result.scalar_one_or_none() is not None:
            return
        any_binding = await db.execute(select(UserAccessBinding).limit(1))
        if any_binding.scalar_one_or_none() is None:
            return
    raise HTTPException(
        status_code=status.HTTP_403_FORBIDDEN,
        detail="No project binding found",
    )


# ---------------------------------------------------------------------------
# Schemas
# ---------------------------------------------------------------------------


class AgentConfigUpsert(BaseModel):
    enabled: bool = False
    display_name: Optional[str] = None
    project_brief: Optional[str] = None
    agent_role: str = "data analyst"
    tone_preset: str = Field(default="professional", pattern="^(professional|friendly)$")
    tone_overrides: Optional[str] = None
    brand_guidelines: Optional[str] = None
    safety_policy: Optional[str] = None
    content_rules: Optional[str] = None
    default_locale: Optional[str] = None
    disclosure_text: Optional[str] = None
    webhook_url: Optional[str] = None
    primary_model_id: Optional[UUID] = None
    answer_llm_config_id: Optional[UUID] = None
    judge_llm_config_id: Optional[UUID] = None
    aggregate_llm_config_id: Optional[UUID] = None
    glossary_llm_config_id: Optional[UUID] = None
    judge_mode: str = Field(default="async", pattern="^(async|sync)$")
    judge_rubric_id: Optional[UUID] = None
    judge_block_visibility: str = Field(
        default="transparent", pattern="^(transparent|opaque)$"
    )
    show_thought_process: bool = True
    show_semantic_query: bool = True
    show_physical_query: bool = True
    feedback_enabled: bool = True
    conversation_retention_days: int = 30
    enable_agent_log_screen: bool = False
    session_history_depth: int = 20
    daily_token_budget: int = 0
    daily_cost_budget_usd: float = 0.0
    max_query_complexity: int = 0
    agent_output_format: str = Field(
        default="json", pattern="^(json|plain|markup|html|rich_html)$"
    )
    chart_type_selector: str = Field(
        default="auto", pattern="^(none|llm|auto)$"
    )
    chart_renderer: str = Field(default="echarts", pattern="^(echarts|html)$")
    chart_max_rows: int = Field(default=500, ge=1)
    chart_color_palette: str = Field(
        default="default",
        pattern="^(default|tessallite|muted|high_contrast|colorblind_safe)$",
    )
    chart_size: str = Field(default="md", pattern="^(sm|md|lg)$")
    include_data_table: bool = True
    max_compound_steps: int = Field(default=3, ge=2, le=5)


class AgentConfigResponse(AgentConfigUpsert):
    model_config = ConfigDict(from_attributes=True)

    id: UUID
    project_id: UUID


class AgentConfigPatch(BaseModel):
    enabled: Optional[bool] = None
    display_name: Optional[str] = None
    project_brief: Optional[str] = None
    agent_role: Optional[str] = None
    tone_preset: Optional[str] = Field(default=None, pattern="^(professional|friendly)$")
    tone_overrides: Optional[str] = None
    brand_guidelines: Optional[str] = None
    safety_policy: Optional[str] = None
    content_rules: Optional[str] = None
    default_locale: Optional[str] = None
    disclosure_text: Optional[str] = None
    webhook_url: Optional[str] = None
    primary_model_id: Optional[UUID] = None
    answer_llm_config_id: Optional[UUID] = None
    judge_llm_config_id: Optional[UUID] = None
    aggregate_llm_config_id: Optional[UUID] = None
    glossary_llm_config_id: Optional[UUID] = None
    judge_mode: Optional[str] = Field(default=None, pattern="^(async|sync)$")
    judge_rubric_id: Optional[UUID] = None
    judge_block_visibility: Optional[str] = Field(
        default=None, pattern="^(transparent|opaque)$"
    )
    show_thought_process: Optional[bool] = None
    show_semantic_query: Optional[bool] = None
    show_physical_query: Optional[bool] = None
    feedback_enabled: Optional[bool] = None
    conversation_retention_days: Optional[int] = None
    enable_agent_log_screen: Optional[bool] = None
    session_history_depth: Optional[int] = None
    daily_token_budget: Optional[int] = None
    daily_cost_budget_usd: Optional[float] = None
    max_query_complexity: Optional[int] = None
    agent_output_format: Optional[str] = Field(
        default=None, pattern="^(json|plain|markup|html|rich_html)$"
    )
    chart_type_selector: Optional[str] = Field(
        default=None, pattern="^(none|llm|auto)$"
    )
    chart_renderer: Optional[str] = Field(
        default=None, pattern="^(echarts|html)$"
    )
    chart_max_rows: Optional[int] = Field(default=None, ge=1)
    chart_color_palette: Optional[str] = Field(
        default=None,
        pattern="^(default|tessallite|muted|high_contrast|colorblind_safe)$",
    )
    chart_size: Optional[str] = Field(default=None, pattern="^(sm|md|lg)$")
    include_data_table: Optional[bool] = None
    max_compound_steps: Optional[int] = Field(default=None, ge=2, le=5)


class AgentModelContextUpsert(BaseModel):
    model_overview: Optional[str] = None
    analytical_capabilities: Optional[str] = None
    abbreviation_conflict_rules: Optional[str] = None
    example_questions: list = Field(default_factory=list)


class AgentModelContextResponse(AgentModelContextUpsert):
    model_config = ConfigDict(from_attributes=True)

    project_id: UUID
    model_id: UUID
    aggregates_summary: list = Field(default_factory=list)
    calendar_aliases: list = Field(default_factory=list)
    dimension_aliases: list = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------


def _validate_for_enable(body: AgentConfigUpsert, allow_list_count: int) -> None:
    """Enabling requires an LLM config and at least one allow-listed model."""
    if not body.enabled:
        return
    missing = []
    if body.answer_llm_config_id is None:
        missing.append("answer_llm_config_id")
    if allow_list_count < 1:
        missing.append("model_ids")
    if missing:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Cannot enable agent: missing fields {missing}",
        )


# ---------------------------------------------------------------------------
# Endpoints — config
# ---------------------------------------------------------------------------


@router.get("/config", response_model=AgentConfigResponse)
async def get_agent_config(
    project_id: UUID,
    current_user: CurrentUser = Depends(forbid_embed_user),
) -> AgentConfigResponse:
    await _require_project_viewer(project_id, current_user)
    async for db in get_tenant_db(current_user.tenant_id):
        result = await db.execute(
            select(ProjectAgentConfig).where(
                ProjectAgentConfig.project_id == project_id
            )
        )
        record = result.scalar_one_or_none()
        if record is None:
            raise HTTPException(status_code=404, detail="Agent not configured")
        return AgentConfigResponse.model_validate(record)
    raise HTTPException(status_code=500, detail="DB session exhausted")


@router.patch("/config", response_model=AgentConfigResponse)
async def patch_agent_config(
    project_id: UUID,
    body: AgentConfigPatch,
    current_user: CurrentUser = Depends(forbid_embed_user),
) -> AgentConfigResponse:
    await _require_project_modeller(project_id, current_user)
    async for db in get_tenant_db(current_user.tenant_id):
        result = await db.execute(
            select(ProjectAgentConfig).where(
                ProjectAgentConfig.project_id == project_id
            )
        )
        record = result.scalar_one_or_none()
        if record is None:
            raise HTTPException(status_code=404, detail="Agent not configured")
        for k, v in body.model_dump(exclude_unset=True).items():
            setattr(record, k, v)
        if getattr(record, "enabled", False):
            count_result = await db.execute(
                select(ProjectAgentModel).where(
                    ProjectAgentModel.project_id == project_id
                )
            )
            allow_count = len(count_result.scalars().all())
            full_body = AgentConfigResponse.model_validate(record)
            _validate_for_enable(full_body, allow_count)
        await db.commit()
        await db.refresh(record)
        return AgentConfigResponse.model_validate(record)
    raise HTTPException(status_code=500, detail="DB session exhausted")


@router.put(
    "/config",
    response_model=AgentConfigResponse,
    summary="Create or fully replace the project agent config",
    description=(
        "**Full-replace contract (Bug-1029).** This is a true HTTP PUT: the "
        "request body is the complete desired state of the agent config. "
        "Every field omitted from the body is reset to its schema default — "
        "including `enabled` (defaults to `false`, which disables the agent) "
        "and the LLM-config bindings (`answer_llm_config_id` etc., default "
        "`null`). Send the entire object, not a delta.\n\n"
        "For partial updates that touch only specific fields, use "
        "`PATCH /config`, which merges with `exclude_unset` semantics and is "
        "what the SPA uses. A partial PUT will silently clobber omitted "
        "fields."
    ),
)
async def upsert_agent_config(
    project_id: UUID,
    body: AgentConfigUpsert,
    current_user: CurrentUser = Depends(forbid_embed_user),
) -> AgentConfigResponse:
    """Create or fully replace the agent config (PUT = replace, not merge).

    Bug-1029 — `body.model_dump()` is applied without `exclude_unset`, so
    every field absent from the request reverts to its default. This is the
    intended PUT semantics (replace the whole resource); the contract is
    documented on the route above and partial callers must use PATCH.
    """
    await _require_project_modeller(project_id, current_user)
    async for db in get_tenant_db(current_user.tenant_id):
        proj = await db.get(Project, project_id)
        if proj is None:
            raise HTTPException(status_code=404, detail="Project not found")

        result = await db.execute(
            select(ProjectAgentConfig).where(
                ProjectAgentConfig.project_id == project_id
            )
        )
        record = result.scalar_one_or_none()

        count_result = await db.execute(
            select(ProjectAgentModel).where(
                ProjectAgentModel.project_id == project_id
            )
        )
        allow_count = len(count_result.scalars().all())
        _validate_for_enable(body, allow_count)

        first_creation = record is None
        if record is None:
            record = ProjectAgentConfig(project_id=project_id)
            db.add(record)

        incoming = body.model_dump()
        if first_creation:
            for field, default_val in _TEMPLATE_DEFAULTS.items():
                client_val = incoming.get(field)
                if client_val is None or (isinstance(client_val, str) and not client_val.strip()):
                    incoming[field] = default_val

        for k, v in incoming.items():
            setattr(record, k, v)

        if first_creation and incoming.get("judge_rubric_id") is None:
            rubric = AgentJudgeRubric(
                project_id=project_id,
                name="Standard Quality",
                sections=_DEFAULT_RUBRIC_SECTIONS,
            )
            db.add(rubric)
            await db.flush()
            record.judge_rubric_id = rubric.id

        await db.commit()
        await db.refresh(record)
        return AgentConfigResponse.model_validate(record)
    raise HTTPException(status_code=500, detail="DB session exhausted")


# ---------------------------------------------------------------------------
# Endpoints — allow-list (model_ids)
# ---------------------------------------------------------------------------


class AllowListReplace(BaseModel):
    model_ids: list[UUID]


@router.get("/models")
async def list_allow_list(
    project_id: UUID,
    current_user: CurrentUser = Depends(forbid_embed_user),
) -> list[UUID]:
    await _require_project_viewer(project_id, current_user)
    async for db in get_tenant_db(current_user.tenant_id):
        result = await db.execute(
            select(ProjectAgentModel.model_id).where(
                ProjectAgentModel.project_id == project_id
            )
        )
        return [row[0] for row in result.all()]
    raise HTTPException(status_code=500, detail="DB session exhausted")


class SelectableModel(BaseModel):
    """A model the end user may pin to a conversation (id + display name)."""
    id: UUID
    name: str


@router.get("/selectable-models", response_model=list[SelectableModel])
async def list_selectable_models(
    project_id: UUID,
    current_user: CurrentUser = Depends(require_capability("chat")),
) -> list[SelectableModel]:
    """Models a chat caller may pin to a conversation: the project agent
    allow-list, further narrowed to the embed token's persona scope when
    present. Reachable by embed users (unlike GET /models) because it drives the
    in-chat model picker. Uses the same scoping helpers as prompt assembly so
    the picker can only ever offer what the agent would actually accept."""
    # Embed tokens may be restricted to a subset of projects.
    if isinstance(current_user, CurrentEmbedUser):
        if (
            current_user.project_ids is not None
            and str(project_id).lower() not in current_user.project_ids
        ):
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail="Embed token does not grant access to this project",
            )

    # Imported lazily to avoid a circular import at module load (assembler pulls
    # in pipeline-adjacent modules).
    from src.prompt.assembler import (
        _apply_persona_filter,
        _load_model_profiles,
        _load_persona_scopes,
    )

    async for db in get_tenant_db(current_user.tenant_id):
        allow_q = await db.execute(
            select(ProjectAgentModel.model_id).where(
                ProjectAgentModel.project_id == project_id
            )
        )
        allow_ids = [row for row in allow_q.scalars().all()]
        profiles = await _load_model_profiles(db, project_id, allow_ids)

        persona_id = None
        if isinstance(current_user, CurrentEmbedUser) and current_user.persona_id:
            persona_id = UUID(current_user.persona_id)
        if persona_id is not None:
            persona_scopes = await _load_persona_scopes(db, persona_id)
            profiles = _apply_persona_filter(profiles, persona_scopes)

        return [SelectableModel(id=p.id, name=p.display_name) for p in profiles]
    raise HTTPException(status_code=500, detail="DB session exhausted")


@router.put("/models")
async def replace_allow_list(
    project_id: UUID,
    body: AllowListReplace,
    current_user: CurrentUser = Depends(forbid_embed_user),
) -> list[UUID]:
    await _require_project_modeller(project_id, current_user)
    async for db in get_tenant_db(current_user.tenant_id):
        # Validate every model belongs to this project.
        for mid in body.model_ids:
            m = await db.get(Model, mid)
            if m is None or m.project_id != project_id:
                raise HTTPException(
                    status_code=400,
                    detail=f"Model {mid} not in project {project_id}",
                )
        # Replace allow-list atomically.
        existing = await db.execute(
            select(ProjectAgentModel).where(
                ProjectAgentModel.project_id == project_id
            )
        )
        for row in existing.scalars().all():
            await db.delete(row)
        for mid in body.model_ids:
            db.add(ProjectAgentModel(project_id=project_id, model_id=mid))
        await db.commit()
        return list(body.model_ids)
    raise HTTPException(status_code=500, detail="DB session exhausted")


# ---------------------------------------------------------------------------
# Endpoints — per-model context
# ---------------------------------------------------------------------------


@router.get(
    "/model-context/{model_id}",
    response_model=AgentModelContextResponse,
)
async def get_model_context(
    project_id: UUID,
    model_id: UUID,
    current_user: CurrentUser = Depends(forbid_embed_user),
) -> AgentModelContextResponse:
    await _require_project_viewer(project_id, current_user)
    async for db in get_tenant_db(current_user.tenant_id):
        record = await db.get(ProjectAgentModelContext, (project_id, model_id))
        if record is None:
            raise HTTPException(status_code=404, detail="Context not set")
        return AgentModelContextResponse.model_validate(record)
    raise HTTPException(status_code=500, detail="DB session exhausted")


@router.post(
    "/model-context/{model_id}/refresh-derived",
    response_model=AgentModelContextResponse,
)
async def refresh_derived_context(
    project_id: UUID,
    model_id: UUID,
    current_user: CurrentUser = Depends(forbid_embed_user),
) -> AgentModelContextResponse:
    """Recompute aggregates_summary / calendar_aliases / dimension_aliases
    from current semantic-layer state. Called by the model-service after a
    publish, or directly by the modeller from the agent panel."""
    await _require_project_modeller(project_id, current_user)
    async for db in get_tenant_db(current_user.tenant_id):
        record = await derive_model_context(db, project_id, model_id)
        if record is None:
            raise HTTPException(
                status_code=404,
                detail="Context row not found — open the model-context dialog first.",
            )
        return AgentModelContextResponse.model_validate(record)
    raise HTTPException(status_code=500, detail="DB session exhausted")


@router.post(
    "/refresh-derived",
    response_model=list[AgentModelContextResponse],
)
async def refresh_all_derived(
    project_id: UUID,
    current_user: CurrentUser = Depends(forbid_embed_user),
) -> list[AgentModelContextResponse]:
    await _require_project_modeller(project_id, current_user)
    async for db in get_tenant_db(current_user.tenant_id):
        rows = await derive_all_for_project(db, project_id)
        return [AgentModelContextResponse.model_validate(r) for r in rows]
    raise HTTPException(status_code=500, detail="DB session exhausted")


@router.put(
    "/model-context/{model_id}",
    response_model=AgentModelContextResponse,
)
async def upsert_model_context(
    project_id: UUID,
    model_id: UUID,
    body: AgentModelContextUpsert,
    current_user: CurrentUser = Depends(forbid_embed_user),
) -> AgentModelContextResponse:
    await _require_project_modeller(project_id, current_user)
    async for db in get_tenant_db(current_user.tenant_id):
        m = await db.get(Model, model_id)
        if m is None or m.project_id != project_id:
            raise HTTPException(
                status_code=400,
                detail=f"Model {model_id} not in project {project_id}",
            )
        record = await db.get(ProjectAgentModelContext, (project_id, model_id))
        if record is None:
            record = ProjectAgentModelContext(
                project_id=project_id, model_id=model_id
            )
            db.add(record)
        for k, v in body.model_dump().items():
            setattr(record, k, v)
        await db.commit()
        await db.refresh(record)
        return AgentModelContextResponse.model_validate(record)
    raise HTTPException(status_code=500, detail="DB session exhausted")
